/*
 * generated by Xtext 2.15.0
 */
package eu.jgen.notes.dmw.lite.mdl.ui;

import com.google.inject.Injector;
import eu.jgen.notes.dmw.lite.mdl.ui.internal.MdlActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ModelExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(MdlActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		MdlActivator activator = MdlActivator.getInstance();
		return activator != null ? activator.getInjector(MdlActivator.EU_JGEN_NOTES_DMW_LITE_MDL_MODEL) : null;
	}

}
