/*
 * generated by Xtext 2.15.0
 */
package eu.jgen.notes.dmw.lite.mdl.ui.tests;

import com.google.inject.Injector;
import eu.jgen.notes.dmw.lite.mdl.ui.internal.MdlActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class ModelUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MdlActivator.getInstance().getInjector("eu.jgen.notes.dmw.lite.mdl.Model");
	}

}
