/*
 * generated by Xtext 2.21.0
 */
package eu.jgen.notes.dmw.lite.mdl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ModelAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("eu/jgen/notes/dmw/lite/mdl/parser/antlr/internal/InternalModel.tokens");
	}
}
