/**
 * generated by Xtext 2.15.0
 */
package eu.jgen.notes.dmw.lite.mdl;

import eu.jgen.notes.dmw.lite.mdl.ModelStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class ModelStandaloneSetup extends ModelStandaloneSetupGenerated {
  public static void doSetup() {
    new ModelStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
