/**
 * generated by Xtext 2.15.0
 */
package eu.jgen.notes.dmw.lite.base.lang.impl;

import eu.jgen.notes.dmw.lite.base.lang.LangFactory;
import eu.jgen.notes.dmw.lite.base.lang.LangPackage;
import eu.jgen.notes.dmw.lite.base.lang.YAccessLevel;
import eu.jgen.notes.dmw.lite.base.lang.YAndExpression;
import eu.jgen.notes.dmw.lite.base.lang.YArgument;
import eu.jgen.notes.dmw.lite.base.lang.YAssignment;
import eu.jgen.notes.dmw.lite.base.lang.YAssociateStatement;
import eu.jgen.notes.dmw.lite.base.lang.YBlock;
import eu.jgen.notes.dmw.lite.base.lang.YBoolConstant;
import eu.jgen.notes.dmw.lite.base.lang.YClass;
import eu.jgen.notes.dmw.lite.base.lang.YComparisonExpression;
import eu.jgen.notes.dmw.lite.base.lang.YCreateStatement;
import eu.jgen.notes.dmw.lite.base.lang.YDeleteStatement;
import eu.jgen.notes.dmw.lite.base.lang.YDisassociateStatement;
import eu.jgen.notes.dmw.lite.base.lang.YEqualityExpression;
import eu.jgen.notes.dmw.lite.base.lang.YExpression;
import eu.jgen.notes.dmw.lite.base.lang.YForInStatement;
import eu.jgen.notes.dmw.lite.base.lang.YFunction;
import eu.jgen.notes.dmw.lite.base.lang.YIfStatement;
import eu.jgen.notes.dmw.lite.base.lang.YIntConstant;
import eu.jgen.notes.dmw.lite.base.lang.YJoin;
import eu.jgen.notes.dmw.lite.base.lang.YJoinDef;
import eu.jgen.notes.dmw.lite.base.lang.YMember;
import eu.jgen.notes.dmw.lite.base.lang.YMemberSelection;
import eu.jgen.notes.dmw.lite.base.lang.YMinus;
import eu.jgen.notes.dmw.lite.base.lang.YMulOrDiv;
import eu.jgen.notes.dmw.lite.base.lang.YNamedElement;
import eu.jgen.notes.dmw.lite.base.lang.YNew;
import eu.jgen.notes.dmw.lite.base.lang.YNot;
import eu.jgen.notes.dmw.lite.base.lang.YNull;
import eu.jgen.notes.dmw.lite.base.lang.YOrExpression;
import eu.jgen.notes.dmw.lite.base.lang.YParameter;
import eu.jgen.notes.dmw.lite.base.lang.YParenties;
import eu.jgen.notes.dmw.lite.base.lang.YPlus;
import eu.jgen.notes.dmw.lite.base.lang.YProperty;
import eu.jgen.notes.dmw.lite.base.lang.YReadEachStatement;
import eu.jgen.notes.dmw.lite.base.lang.YReadStatement;
import eu.jgen.notes.dmw.lite.base.lang.YRepeatWhileStatement;
import eu.jgen.notes.dmw.lite.base.lang.YReturn;
import eu.jgen.notes.dmw.lite.base.lang.YSelf;
import eu.jgen.notes.dmw.lite.base.lang.YStatement;
import eu.jgen.notes.dmw.lite.base.lang.YStringConstant;
import eu.jgen.notes.dmw.lite.base.lang.YStructRefPair;
import eu.jgen.notes.dmw.lite.base.lang.YSuper;
import eu.jgen.notes.dmw.lite.base.lang.YSwitchCase;
import eu.jgen.notes.dmw.lite.base.lang.YSwitchStatement;
import eu.jgen.notes.dmw.lite.base.lang.YSymbol;
import eu.jgen.notes.dmw.lite.base.lang.YSymbolRef;
import eu.jgen.notes.dmw.lite.base.lang.YTuples;
import eu.jgen.notes.dmw.lite.base.lang.YUpdateStatement;
import eu.jgen.notes.dmw.lite.base.lang.YVariableDeclaration;
import eu.jgen.notes.dmw.lite.base.lang.YWhere;
import eu.jgen.notes.dmw.lite.base.lang.YWhileStatement;
import eu.jgen.notes.dmw.lite.base.lang.YWidget;

import eu.jgen.notes.dmw.lite.mdl.model.ModelPackage;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class LangPackageImpl extends EPackageImpl implements LangPackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yWidgetEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yParameterEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yArgumentEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yClassEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yMemberEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yPropertyEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yTuplesEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yFunctionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yBlockEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yStatementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yVariableDeclarationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yReturnEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yIfStatementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass ySwitchStatementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass ySwitchCaseEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass ySymbolEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yNamedElementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yExpressionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yReadStatementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yReadEachStatementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yCreateStatementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yUpdateStatementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yDeleteStatementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yAssociateStatementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yDisassociateStatementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yStructRefPairEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yJoinEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yJoinDefEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yWhereEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yWhileStatementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yRepeatWhileStatementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yForInStatementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yAssignmentEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yMemberSelectionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yOrExpressionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yAndExpressionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yEqualityExpressionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yComparisonExpressionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yPlusEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yMinusEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yMulOrDivEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yParentiesEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yNotEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yStringConstantEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yIntConstantEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yBoolConstantEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass ySelfEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass ySuperEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yNullEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass ySymbolRefEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yNewEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum yAccessLevelEEnum = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see eu.jgen.notes.dmw.lite.base.lang.LangPackage#eNS_URI
   * @see #init()
   * @generated
   */
  private LangPackageImpl()
  {
    super(eNS_URI, LangFactory.eINSTANCE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   *
   * <p>This method is used to initialize {@link LangPackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static LangPackage init()
  {
    if (isInited) return (LangPackage)EPackage.Registry.INSTANCE.getEPackage(LangPackage.eNS_URI);

    // Obtain or create and register package
    Object registeredLangPackage = EPackage.Registry.INSTANCE.get(eNS_URI);
    LangPackageImpl theLangPackage = registeredLangPackage instanceof LangPackageImpl ? (LangPackageImpl)registeredLangPackage : new LangPackageImpl();

    isInited = true;

    // Initialize simple dependencies
    ModelPackage.eINSTANCE.eClass();

    // Create package meta-data objects
    theLangPackage.createPackageContents();

    // Initialize created meta-data
    theLangPackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theLangPackage.freeze();

    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(LangPackage.eNS_URI, theLangPackage);
    return theLangPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYWidget()
  {
    return yWidgetEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getYWidget_Name()
  {
    return (EAttribute)yWidgetEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYWidget_Imports()
  {
    return (EReference)yWidgetEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYWidget_Classes()
  {
    return (EReference)yWidgetEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYParameter()
  {
    return yParameterEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYArgument()
  {
    return yArgumentEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getYArgument_Name()
  {
    return (EAttribute)yArgumentEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getYArgument_Value()
  {
    return (EAttribute)yArgumentEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYClass()
  {
    return yClassEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYClass_Superclass()
  {
    return (EReference)yClassEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYClass_EntityRef()
  {
    return (EReference)yClassEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYClass_Inners()
  {
    return (EReference)yClassEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYClass_Members()
  {
    return (EReference)yClassEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYMember()
  {
    return yMemberEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getYMember_Access()
  {
    return (EAttribute)yMemberEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYMember_Type()
  {
    return (EReference)yMemberEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYProperty()
  {
    return yPropertyEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYProperty_Tuples()
  {
    return (EReference)yPropertyEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getYProperty_Optional()
  {
    return (EAttribute)yPropertyEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYProperty_AttrRef()
  {
    return (EReference)yPropertyEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYTuples()
  {
    return yTuplesEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYTuples_Includes()
  {
    return (EReference)yTuplesEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYFunction()
  {
    return yFunctionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYFunction_Params()
  {
    return (EReference)yFunctionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getYFunction_Returnvalue()
  {
    return (EAttribute)yFunctionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYFunction_Body()
  {
    return (EReference)yFunctionEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYBlock()
  {
    return yBlockEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYBlock_Statements()
  {
    return (EReference)yBlockEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYStatement()
  {
    return yStatementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYVariableDeclaration()
  {
    return yVariableDeclarationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYVariableDeclaration_Expression()
  {
    return (EReference)yVariableDeclarationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYReturn()
  {
    return yReturnEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYReturn_Expression()
  {
    return (EReference)yReturnEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYIfStatement()
  {
    return yIfStatementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYIfStatement_Expression()
  {
    return (EReference)yIfStatementEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYIfStatement_ThenBlock()
  {
    return (EReference)yIfStatementEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYIfStatement_ElseBlock()
  {
    return (EReference)yIfStatementEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYSwitchStatement()
  {
    return ySwitchStatementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYSwitchStatement_SwitchExpression()
  {
    return (EReference)ySwitchStatementEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYSwitchStatement_Cases()
  {
    return (EReference)ySwitchStatementEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYSwitchStatement_Default()
  {
    return (EReference)ySwitchStatementEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYSwitchCase()
  {
    return ySwitchCaseEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYSwitchCase_CaseExpression()
  {
    return (EReference)ySwitchCaseEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYSwitchCase_Then()
  {
    return (EReference)ySwitchCaseEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYSymbol()
  {
    return ySymbolEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYSymbol_Type()
  {
    return (EReference)ySymbolEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYNamedElement()
  {
    return yNamedElementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getYNamedElement_Name()
  {
    return (EAttribute)yNamedElementEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYExpression()
  {
    return yExpressionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYReadStatement()
  {
    return yReadStatementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYReadStatement_Structs()
  {
    return (EReference)yReadStatementEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYReadStatement_Joinclause()
  {
    return (EReference)yReadStatementEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYReadStatement_Whereclause()
  {
    return (EReference)yReadStatementEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYReadStatement_Success()
  {
    return (EReference)yReadStatementEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYReadStatement_Notfound()
  {
    return (EReference)yReadStatementEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYReadEachStatement()
  {
    return yReadEachStatementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYReadEachStatement_Structs()
  {
    return (EReference)yReadEachStatementEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYReadEachStatement_Joinclause()
  {
    return (EReference)yReadEachStatementEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYReadEachStatement_Whereclause()
  {
    return (EReference)yReadEachStatementEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYReadEachStatement_Target()
  {
    return (EReference)yReadEachStatementEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYReadEachStatement_Success()
  {
    return (EReference)yReadEachStatementEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYCreateStatement()
  {
    return yCreateStatementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYCreateStatement_Struct()
  {
    return (EReference)yCreateStatementEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYCreateStatement_SetBlock()
  {
    return (EReference)yCreateStatementEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYCreateStatement_Success()
  {
    return (EReference)yCreateStatementEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYCreateStatement_AlreadyExist()
  {
    return (EReference)yCreateStatementEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYUpdateStatement()
  {
    return yUpdateStatementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYUpdateStatement_Struct()
  {
    return (EReference)yUpdateStatementEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYUpdateStatement_SetBlock()
  {
    return (EReference)yUpdateStatementEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYUpdateStatement_Success()
  {
    return (EReference)yUpdateStatementEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYDeleteStatement()
  {
    return yDeleteStatementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYDeleteStatement_Struct()
  {
    return (EReference)yDeleteStatementEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYAssociateStatement()
  {
    return yAssociateStatementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYAssociateStatement_Struct()
  {
    return (EReference)yAssociateStatementEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYAssociateStatement_Joinref()
  {
    return (EReference)yAssociateStatementEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYDisassociateStatement()
  {
    return yDisassociateStatementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYDisassociateStatement_Struct()
  {
    return (EReference)yDisassociateStatementEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYDisassociateStatement_Joinref()
  {
    return (EReference)yDisassociateStatementEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYStructRefPair()
  {
    return yStructRefPairEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYStructRefPair_Structproperty()
  {
    return (EReference)yStructRefPairEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYStructRefPair_Structclass()
  {
    return (EReference)yStructRefPairEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYJoin()
  {
    return yJoinEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYJoin_Joindefs()
  {
    return (EReference)yJoinEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYJoinDef()
  {
    return yJoinDefEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYJoinDef_FromView()
  {
    return (EReference)yJoinDefEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYJoinDef_RelRef()
  {
    return (EReference)yJoinDefEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYJoinDef_ToView()
  {
    return (EReference)yJoinDefEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYWhere()
  {
    return yWhereEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYWhere_Expression()
  {
    return (EReference)yWhereEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYWhileStatement()
  {
    return yWhileStatementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYWhileStatement_Expression()
  {
    return (EReference)yWhileStatementEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYWhileStatement_Body()
  {
    return (EReference)yWhileStatementEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYRepeatWhileStatement()
  {
    return yRepeatWhileStatementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYRepeatWhileStatement_Body()
  {
    return (EReference)yRepeatWhileStatementEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYRepeatWhileStatement_Expression()
  {
    return (EReference)yRepeatWhileStatementEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYForInStatement()
  {
    return yForInStatementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYForInStatement_Item()
  {
    return (EReference)yForInStatementEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYForInStatement_Collection()
  {
    return (EReference)yForInStatementEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYForInStatement_Body()
  {
    return (EReference)yForInStatementEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYAssignment()
  {
    return yAssignmentEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYAssignment_Left()
  {
    return (EReference)yAssignmentEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYAssignment_Right()
  {
    return (EReference)yAssignmentEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYMemberSelection()
  {
    return yMemberSelectionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYMemberSelection_Receiver()
  {
    return (EReference)yMemberSelectionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYMemberSelection_Member()
  {
    return (EReference)yMemberSelectionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getYMemberSelection_Functioninvocation()
  {
    return (EAttribute)yMemberSelectionEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYMemberSelection_Args()
  {
    return (EReference)yMemberSelectionEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYOrExpression()
  {
    return yOrExpressionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYOrExpression_Left()
  {
    return (EReference)yOrExpressionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYOrExpression_Right()
  {
    return (EReference)yOrExpressionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYAndExpression()
  {
    return yAndExpressionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYAndExpression_Left()
  {
    return (EReference)yAndExpressionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYAndExpression_Right()
  {
    return (EReference)yAndExpressionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYEqualityExpression()
  {
    return yEqualityExpressionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYEqualityExpression_Left()
  {
    return (EReference)yEqualityExpressionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getYEqualityExpression_Op()
  {
    return (EAttribute)yEqualityExpressionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYEqualityExpression_Right()
  {
    return (EReference)yEqualityExpressionEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYComparisonExpression()
  {
    return yComparisonExpressionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYComparisonExpression_Left()
  {
    return (EReference)yComparisonExpressionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getYComparisonExpression_Op()
  {
    return (EAttribute)yComparisonExpressionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYComparisonExpression_Right()
  {
    return (EReference)yComparisonExpressionEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYPlus()
  {
    return yPlusEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYPlus_Left()
  {
    return (EReference)yPlusEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYPlus_Right()
  {
    return (EReference)yPlusEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYMinus()
  {
    return yMinusEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYMinus_Left()
  {
    return (EReference)yMinusEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYMinus_Right()
  {
    return (EReference)yMinusEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYMulOrDiv()
  {
    return yMulOrDivEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYMulOrDiv_Left()
  {
    return (EReference)yMulOrDivEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getYMulOrDiv_Op()
  {
    return (EAttribute)yMulOrDivEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYMulOrDiv_Right()
  {
    return (EReference)yMulOrDivEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYParenties()
  {
    return yParentiesEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYParenties_A()
  {
    return (EReference)yParentiesEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYNot()
  {
    return yNotEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYNot_Expression()
  {
    return (EReference)yNotEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYStringConstant()
  {
    return yStringConstantEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getYStringConstant_Value()
  {
    return (EAttribute)yStringConstantEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYIntConstant()
  {
    return yIntConstantEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getYIntConstant_Value()
  {
    return (EAttribute)yIntConstantEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYBoolConstant()
  {
    return yBoolConstantEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getYBoolConstant_Value()
  {
    return (EAttribute)yBoolConstantEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYSelf()
  {
    return ySelfEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYSuper()
  {
    return ySuperEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYNull()
  {
    return yNullEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYSymbolRef()
  {
    return ySymbolRefEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYSymbolRef_Symbol()
  {
    return (EReference)ySymbolRefEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYNew()
  {
    return yNewEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYNew_Type()
  {
    return (EReference)yNewEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYNew_Arguments()
  {
    return (EReference)yNewEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EEnum getYAccessLevel()
  {
    return yAccessLevelEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public LangFactory getLangFactory()
  {
    return (LangFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    yWidgetEClass = createEClass(YWIDGET);
    createEAttribute(yWidgetEClass, YWIDGET__NAME);
    createEReference(yWidgetEClass, YWIDGET__IMPORTS);
    createEReference(yWidgetEClass, YWIDGET__CLASSES);

    yParameterEClass = createEClass(YPARAMETER);

    yArgumentEClass = createEClass(YARGUMENT);
    createEAttribute(yArgumentEClass, YARGUMENT__NAME);
    createEAttribute(yArgumentEClass, YARGUMENT__VALUE);

    yClassEClass = createEClass(YCLASS);
    createEReference(yClassEClass, YCLASS__SUPERCLASS);
    createEReference(yClassEClass, YCLASS__ENTITY_REF);
    createEReference(yClassEClass, YCLASS__INNERS);
    createEReference(yClassEClass, YCLASS__MEMBERS);

    yMemberEClass = createEClass(YMEMBER);
    createEAttribute(yMemberEClass, YMEMBER__ACCESS);
    createEReference(yMemberEClass, YMEMBER__TYPE);

    yPropertyEClass = createEClass(YPROPERTY);
    createEReference(yPropertyEClass, YPROPERTY__TUPLES);
    createEAttribute(yPropertyEClass, YPROPERTY__OPTIONAL);
    createEReference(yPropertyEClass, YPROPERTY__ATTR_REF);

    yTuplesEClass = createEClass(YTUPLES);
    createEReference(yTuplesEClass, YTUPLES__INCLUDES);

    yFunctionEClass = createEClass(YFUNCTION);
    createEReference(yFunctionEClass, YFUNCTION__PARAMS);
    createEAttribute(yFunctionEClass, YFUNCTION__RETURNVALUE);
    createEReference(yFunctionEClass, YFUNCTION__BODY);

    yBlockEClass = createEClass(YBLOCK);
    createEReference(yBlockEClass, YBLOCK__STATEMENTS);

    yStatementEClass = createEClass(YSTATEMENT);

    yVariableDeclarationEClass = createEClass(YVARIABLE_DECLARATION);
    createEReference(yVariableDeclarationEClass, YVARIABLE_DECLARATION__EXPRESSION);

    yReturnEClass = createEClass(YRETURN);
    createEReference(yReturnEClass, YRETURN__EXPRESSION);

    yIfStatementEClass = createEClass(YIF_STATEMENT);
    createEReference(yIfStatementEClass, YIF_STATEMENT__EXPRESSION);
    createEReference(yIfStatementEClass, YIF_STATEMENT__THEN_BLOCK);
    createEReference(yIfStatementEClass, YIF_STATEMENT__ELSE_BLOCK);

    ySwitchStatementEClass = createEClass(YSWITCH_STATEMENT);
    createEReference(ySwitchStatementEClass, YSWITCH_STATEMENT__SWITCH_EXPRESSION);
    createEReference(ySwitchStatementEClass, YSWITCH_STATEMENT__CASES);
    createEReference(ySwitchStatementEClass, YSWITCH_STATEMENT__DEFAULT);

    ySwitchCaseEClass = createEClass(YSWITCH_CASE);
    createEReference(ySwitchCaseEClass, YSWITCH_CASE__CASE_EXPRESSION);
    createEReference(ySwitchCaseEClass, YSWITCH_CASE__THEN);

    ySymbolEClass = createEClass(YSYMBOL);
    createEReference(ySymbolEClass, YSYMBOL__TYPE);

    yNamedElementEClass = createEClass(YNAMED_ELEMENT);
    createEAttribute(yNamedElementEClass, YNAMED_ELEMENT__NAME);

    yExpressionEClass = createEClass(YEXPRESSION);

    yReadStatementEClass = createEClass(YREAD_STATEMENT);
    createEReference(yReadStatementEClass, YREAD_STATEMENT__STRUCTS);
    createEReference(yReadStatementEClass, YREAD_STATEMENT__JOINCLAUSE);
    createEReference(yReadStatementEClass, YREAD_STATEMENT__WHERECLAUSE);
    createEReference(yReadStatementEClass, YREAD_STATEMENT__SUCCESS);
    createEReference(yReadStatementEClass, YREAD_STATEMENT__NOTFOUND);

    yReadEachStatementEClass = createEClass(YREAD_EACH_STATEMENT);
    createEReference(yReadEachStatementEClass, YREAD_EACH_STATEMENT__STRUCTS);
    createEReference(yReadEachStatementEClass, YREAD_EACH_STATEMENT__JOINCLAUSE);
    createEReference(yReadEachStatementEClass, YREAD_EACH_STATEMENT__WHERECLAUSE);
    createEReference(yReadEachStatementEClass, YREAD_EACH_STATEMENT__TARGET);
    createEReference(yReadEachStatementEClass, YREAD_EACH_STATEMENT__SUCCESS);

    yCreateStatementEClass = createEClass(YCREATE_STATEMENT);
    createEReference(yCreateStatementEClass, YCREATE_STATEMENT__STRUCT);
    createEReference(yCreateStatementEClass, YCREATE_STATEMENT__SET_BLOCK);
    createEReference(yCreateStatementEClass, YCREATE_STATEMENT__SUCCESS);
    createEReference(yCreateStatementEClass, YCREATE_STATEMENT__ALREADY_EXIST);

    yUpdateStatementEClass = createEClass(YUPDATE_STATEMENT);
    createEReference(yUpdateStatementEClass, YUPDATE_STATEMENT__STRUCT);
    createEReference(yUpdateStatementEClass, YUPDATE_STATEMENT__SET_BLOCK);
    createEReference(yUpdateStatementEClass, YUPDATE_STATEMENT__SUCCESS);

    yDeleteStatementEClass = createEClass(YDELETE_STATEMENT);
    createEReference(yDeleteStatementEClass, YDELETE_STATEMENT__STRUCT);

    yAssociateStatementEClass = createEClass(YASSOCIATE_STATEMENT);
    createEReference(yAssociateStatementEClass, YASSOCIATE_STATEMENT__STRUCT);
    createEReference(yAssociateStatementEClass, YASSOCIATE_STATEMENT__JOINREF);

    yDisassociateStatementEClass = createEClass(YDISASSOCIATE_STATEMENT);
    createEReference(yDisassociateStatementEClass, YDISASSOCIATE_STATEMENT__STRUCT);
    createEReference(yDisassociateStatementEClass, YDISASSOCIATE_STATEMENT__JOINREF);

    yStructRefPairEClass = createEClass(YSTRUCT_REF_PAIR);
    createEReference(yStructRefPairEClass, YSTRUCT_REF_PAIR__STRUCTPROPERTY);
    createEReference(yStructRefPairEClass, YSTRUCT_REF_PAIR__STRUCTCLASS);

    yJoinEClass = createEClass(YJOIN);
    createEReference(yJoinEClass, YJOIN__JOINDEFS);

    yJoinDefEClass = createEClass(YJOIN_DEF);
    createEReference(yJoinDefEClass, YJOIN_DEF__FROM_VIEW);
    createEReference(yJoinDefEClass, YJOIN_DEF__REL_REF);
    createEReference(yJoinDefEClass, YJOIN_DEF__TO_VIEW);

    yWhereEClass = createEClass(YWHERE);
    createEReference(yWhereEClass, YWHERE__EXPRESSION);

    yWhileStatementEClass = createEClass(YWHILE_STATEMENT);
    createEReference(yWhileStatementEClass, YWHILE_STATEMENT__EXPRESSION);
    createEReference(yWhileStatementEClass, YWHILE_STATEMENT__BODY);

    yRepeatWhileStatementEClass = createEClass(YREPEAT_WHILE_STATEMENT);
    createEReference(yRepeatWhileStatementEClass, YREPEAT_WHILE_STATEMENT__BODY);
    createEReference(yRepeatWhileStatementEClass, YREPEAT_WHILE_STATEMENT__EXPRESSION);

    yForInStatementEClass = createEClass(YFOR_IN_STATEMENT);
    createEReference(yForInStatementEClass, YFOR_IN_STATEMENT__ITEM);
    createEReference(yForInStatementEClass, YFOR_IN_STATEMENT__COLLECTION);
    createEReference(yForInStatementEClass, YFOR_IN_STATEMENT__BODY);

    yAssignmentEClass = createEClass(YASSIGNMENT);
    createEReference(yAssignmentEClass, YASSIGNMENT__LEFT);
    createEReference(yAssignmentEClass, YASSIGNMENT__RIGHT);

    yMemberSelectionEClass = createEClass(YMEMBER_SELECTION);
    createEReference(yMemberSelectionEClass, YMEMBER_SELECTION__RECEIVER);
    createEReference(yMemberSelectionEClass, YMEMBER_SELECTION__MEMBER);
    createEAttribute(yMemberSelectionEClass, YMEMBER_SELECTION__FUNCTIONINVOCATION);
    createEReference(yMemberSelectionEClass, YMEMBER_SELECTION__ARGS);

    yOrExpressionEClass = createEClass(YOR_EXPRESSION);
    createEReference(yOrExpressionEClass, YOR_EXPRESSION__LEFT);
    createEReference(yOrExpressionEClass, YOR_EXPRESSION__RIGHT);

    yAndExpressionEClass = createEClass(YAND_EXPRESSION);
    createEReference(yAndExpressionEClass, YAND_EXPRESSION__LEFT);
    createEReference(yAndExpressionEClass, YAND_EXPRESSION__RIGHT);

    yEqualityExpressionEClass = createEClass(YEQUALITY_EXPRESSION);
    createEReference(yEqualityExpressionEClass, YEQUALITY_EXPRESSION__LEFT);
    createEAttribute(yEqualityExpressionEClass, YEQUALITY_EXPRESSION__OP);
    createEReference(yEqualityExpressionEClass, YEQUALITY_EXPRESSION__RIGHT);

    yComparisonExpressionEClass = createEClass(YCOMPARISON_EXPRESSION);
    createEReference(yComparisonExpressionEClass, YCOMPARISON_EXPRESSION__LEFT);
    createEAttribute(yComparisonExpressionEClass, YCOMPARISON_EXPRESSION__OP);
    createEReference(yComparisonExpressionEClass, YCOMPARISON_EXPRESSION__RIGHT);

    yPlusEClass = createEClass(YPLUS);
    createEReference(yPlusEClass, YPLUS__LEFT);
    createEReference(yPlusEClass, YPLUS__RIGHT);

    yMinusEClass = createEClass(YMINUS);
    createEReference(yMinusEClass, YMINUS__LEFT);
    createEReference(yMinusEClass, YMINUS__RIGHT);

    yMulOrDivEClass = createEClass(YMUL_OR_DIV);
    createEReference(yMulOrDivEClass, YMUL_OR_DIV__LEFT);
    createEAttribute(yMulOrDivEClass, YMUL_OR_DIV__OP);
    createEReference(yMulOrDivEClass, YMUL_OR_DIV__RIGHT);

    yParentiesEClass = createEClass(YPARENTIES);
    createEReference(yParentiesEClass, YPARENTIES__A);

    yNotEClass = createEClass(YNOT);
    createEReference(yNotEClass, YNOT__EXPRESSION);

    yStringConstantEClass = createEClass(YSTRING_CONSTANT);
    createEAttribute(yStringConstantEClass, YSTRING_CONSTANT__VALUE);

    yIntConstantEClass = createEClass(YINT_CONSTANT);
    createEAttribute(yIntConstantEClass, YINT_CONSTANT__VALUE);

    yBoolConstantEClass = createEClass(YBOOL_CONSTANT);
    createEAttribute(yBoolConstantEClass, YBOOL_CONSTANT__VALUE);

    ySelfEClass = createEClass(YSELF);

    ySuperEClass = createEClass(YSUPER);

    yNullEClass = createEClass(YNULL);

    ySymbolRefEClass = createEClass(YSYMBOL_REF);
    createEReference(ySymbolRefEClass, YSYMBOL_REF__SYMBOL);

    yNewEClass = createEClass(YNEW);
    createEReference(yNewEClass, YNEW__TYPE);
    createEReference(yNewEClass, YNEW__ARGUMENTS);

    // Create enums
    yAccessLevelEEnum = createEEnum(YACCESS_LEVEL);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Obtain other dependent packages
    ModelPackage theModelPackage = (ModelPackage)EPackage.Registry.INSTANCE.getEPackage(ModelPackage.eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes
    yParameterEClass.getESuperTypes().add(this.getYSymbol());
    yClassEClass.getESuperTypes().add(this.getYNamedElement());
    yMemberEClass.getESuperTypes().add(this.getYNamedElement());
    yPropertyEClass.getESuperTypes().add(this.getYMember());
    yFunctionEClass.getESuperTypes().add(this.getYMember());
    yVariableDeclarationEClass.getESuperTypes().add(this.getYStatement());
    yVariableDeclarationEClass.getESuperTypes().add(this.getYSymbol());
    yReturnEClass.getESuperTypes().add(this.getYStatement());
    yIfStatementEClass.getESuperTypes().add(this.getYStatement());
    ySwitchStatementEClass.getESuperTypes().add(this.getYStatement());
    ySymbolEClass.getESuperTypes().add(this.getYNamedElement());
    yExpressionEClass.getESuperTypes().add(this.getYStatement());
    yReadStatementEClass.getESuperTypes().add(this.getYStatement());
    yReadEachStatementEClass.getESuperTypes().add(this.getYStatement());
    yCreateStatementEClass.getESuperTypes().add(this.getYStatement());
    yUpdateStatementEClass.getESuperTypes().add(this.getYStatement());
    yDeleteStatementEClass.getESuperTypes().add(this.getYStatement());
    yAssociateStatementEClass.getESuperTypes().add(this.getYStatement());
    yDisassociateStatementEClass.getESuperTypes().add(this.getYStatement());
    yJoinDefEClass.getESuperTypes().add(this.getYParameter());
    yWhileStatementEClass.getESuperTypes().add(this.getYStatement());
    yRepeatWhileStatementEClass.getESuperTypes().add(this.getYStatement());
    yForInStatementEClass.getESuperTypes().add(this.getYStatement());
    yAssignmentEClass.getESuperTypes().add(this.getYExpression());
    yMemberSelectionEClass.getESuperTypes().add(this.getYExpression());
    yOrExpressionEClass.getESuperTypes().add(this.getYExpression());
    yAndExpressionEClass.getESuperTypes().add(this.getYExpression());
    yEqualityExpressionEClass.getESuperTypes().add(this.getYExpression());
    yComparisonExpressionEClass.getESuperTypes().add(this.getYExpression());
    yPlusEClass.getESuperTypes().add(this.getYExpression());
    yMinusEClass.getESuperTypes().add(this.getYExpression());
    yMulOrDivEClass.getESuperTypes().add(this.getYExpression());
    yParentiesEClass.getESuperTypes().add(this.getYExpression());
    yNotEClass.getESuperTypes().add(this.getYExpression());
    yStringConstantEClass.getESuperTypes().add(this.getYExpression());
    yIntConstantEClass.getESuperTypes().add(this.getYExpression());
    yBoolConstantEClass.getESuperTypes().add(this.getYExpression());
    ySelfEClass.getESuperTypes().add(this.getYExpression());
    ySuperEClass.getESuperTypes().add(this.getYExpression());
    yNullEClass.getESuperTypes().add(this.getYExpression());
    ySymbolRefEClass.getESuperTypes().add(this.getYExpression());
    yNewEClass.getESuperTypes().add(this.getYExpression());

    // Initialize classes and features; add operations and parameters
    initEClass(yWidgetEClass, YWidget.class, "YWidget", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getYWidget_Name(), ecorePackage.getEString(), "name", null, 0, 1, YWidget.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYWidget_Imports(), theModelPackage.getYImport(), null, "imports", null, 0, -1, YWidget.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYWidget_Classes(), this.getYClass(), null, "classes", null, 0, -1, YWidget.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(yParameterEClass, YParameter.class, "YParameter", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(yArgumentEClass, YArgument.class, "YArgument", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getYArgument_Name(), ecorePackage.getEString(), "name", null, 0, 1, YArgument.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getYArgument_Value(), ecorePackage.getEString(), "value", null, 0, 1, YArgument.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(yClassEClass, YClass.class, "YClass", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getYClass_Superclass(), this.getYClass(), null, "superclass", null, 0, 1, YClass.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYClass_EntityRef(), theModelPackage.getYAnnotEntity(), null, "entityRef", null, 0, 1, YClass.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYClass_Inners(), this.getYClass(), null, "inners", null, 0, -1, YClass.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYClass_Members(), this.getYMember(), null, "members", null, 0, -1, YClass.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(yMemberEClass, YMember.class, "YMember", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getYMember_Access(), this.getYAccessLevel(), "access", null, 0, 1, YMember.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYMember_Type(), this.getYClass(), null, "type", null, 0, 1, YMember.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(yPropertyEClass, YProperty.class, "YProperty", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getYProperty_Tuples(), this.getYTuples(), null, "tuples", null, 0, 1, YProperty.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getYProperty_Optional(), ecorePackage.getEBoolean(), "optional", null, 0, 1, YProperty.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYProperty_AttrRef(), theModelPackage.getYAnnotAttribute(), null, "attrRef", null, 0, 1, YProperty.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(yTuplesEClass, YTuples.class, "YTuples", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getYTuples_Includes(), this.getYProperty(), null, "includes", null, 0, -1, YTuples.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(yFunctionEClass, YFunction.class, "YFunction", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getYFunction_Params(), this.getYParameter(), null, "params", null, 0, -1, YFunction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getYFunction_Returnvalue(), ecorePackage.getEBoolean(), "returnvalue", null, 0, 1, YFunction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYFunction_Body(), this.getYBlock(), null, "body", null, 0, 1, YFunction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(yBlockEClass, YBlock.class, "YBlock", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getYBlock_Statements(), this.getYStatement(), null, "statements", null, 0, -1, YBlock.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(yStatementEClass, YStatement.class, "YStatement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(yVariableDeclarationEClass, YVariableDeclaration.class, "YVariableDeclaration", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getYVariableDeclaration_Expression(), this.getYExpression(), null, "expression", null, 0, 1, YVariableDeclaration.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(yReturnEClass, YReturn.class, "YReturn", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getYReturn_Expression(), this.getYExpression(), null, "expression", null, 0, 1, YReturn.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(yIfStatementEClass, YIfStatement.class, "YIfStatement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getYIfStatement_Expression(), this.getYExpression(), null, "expression", null, 0, 1, YIfStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYIfStatement_ThenBlock(), this.getYBlock(), null, "thenBlock", null, 0, 1, YIfStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYIfStatement_ElseBlock(), this.getYBlock(), null, "elseBlock", null, 0, 1, YIfStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(ySwitchStatementEClass, YSwitchStatement.class, "YSwitchStatement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getYSwitchStatement_SwitchExpression(), this.getYExpression(), null, "switchExpression", null, 0, 1, YSwitchStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYSwitchStatement_Cases(), this.getYSwitchCase(), null, "cases", null, 0, -1, YSwitchStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYSwitchStatement_Default(), this.getYBlock(), null, "default", null, 0, 1, YSwitchStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(ySwitchCaseEClass, YSwitchCase.class, "YSwitchCase", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getYSwitchCase_CaseExpression(), this.getYExpression(), null, "caseExpression", null, 0, 1, YSwitchCase.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYSwitchCase_Then(), this.getYBlock(), null, "then", null, 0, 1, YSwitchCase.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(ySymbolEClass, YSymbol.class, "YSymbol", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getYSymbol_Type(), this.getYClass(), null, "type", null, 0, 1, YSymbol.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(yNamedElementEClass, YNamedElement.class, "YNamedElement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getYNamedElement_Name(), ecorePackage.getEString(), "name", null, 0, 1, YNamedElement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(yExpressionEClass, YExpression.class, "YExpression", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(yReadStatementEClass, YReadStatement.class, "YReadStatement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getYReadStatement_Structs(), this.getYStructRefPair(), null, "structs", null, 0, -1, YReadStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYReadStatement_Joinclause(), this.getYJoin(), null, "joinclause", null, 0, 1, YReadStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYReadStatement_Whereclause(), this.getYWhere(), null, "whereclause", null, 0, 1, YReadStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYReadStatement_Success(), this.getYBlock(), null, "success", null, 0, 1, YReadStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYReadStatement_Notfound(), this.getYBlock(), null, "notfound", null, 0, 1, YReadStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(yReadEachStatementEClass, YReadEachStatement.class, "YReadEachStatement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getYReadEachStatement_Structs(), this.getYStructRefPair(), null, "structs", null, 0, -1, YReadEachStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYReadEachStatement_Joinclause(), this.getYJoin(), null, "joinclause", null, 0, 1, YReadEachStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYReadEachStatement_Whereclause(), this.getYWhere(), null, "whereclause", null, 0, 1, YReadEachStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYReadEachStatement_Target(), this.getYProperty(), null, "target", null, 0, 1, YReadEachStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYReadEachStatement_Success(), this.getYBlock(), null, "success", null, 0, 1, YReadEachStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(yCreateStatementEClass, YCreateStatement.class, "YCreateStatement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getYCreateStatement_Struct(), this.getYStructRefPair(), null, "struct", null, 0, 1, YCreateStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYCreateStatement_SetBlock(), this.getYBlock(), null, "setBlock", null, 0, 1, YCreateStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYCreateStatement_Success(), this.getYBlock(), null, "success", null, 0, 1, YCreateStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYCreateStatement_AlreadyExist(), this.getYBlock(), null, "alreadyExist", null, 0, 1, YCreateStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(yUpdateStatementEClass, YUpdateStatement.class, "YUpdateStatement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getYUpdateStatement_Struct(), this.getYStructRefPair(), null, "struct", null, 0, 1, YUpdateStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYUpdateStatement_SetBlock(), this.getYBlock(), null, "setBlock", null, 0, 1, YUpdateStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYUpdateStatement_Success(), this.getYBlock(), null, "success", null, 0, 1, YUpdateStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(yDeleteStatementEClass, YDeleteStatement.class, "YDeleteStatement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getYDeleteStatement_Struct(), this.getYStructRefPair(), null, "struct", null, 0, 1, YDeleteStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(yAssociateStatementEClass, YAssociateStatement.class, "YAssociateStatement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getYAssociateStatement_Struct(), this.getYStructRefPair(), null, "struct", null, 0, 1, YAssociateStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYAssociateStatement_Joinref(), this.getYJoinDef(), null, "joinref", null, 0, 1, YAssociateStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(yDisassociateStatementEClass, YDisassociateStatement.class, "YDisassociateStatement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getYDisassociateStatement_Struct(), this.getYStructRefPair(), null, "struct", null, 0, 1, YDisassociateStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYDisassociateStatement_Joinref(), this.getYJoinDef(), null, "joinref", null, 0, 1, YDisassociateStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(yStructRefPairEClass, YStructRefPair.class, "YStructRefPair", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getYStructRefPair_Structproperty(), this.getYProperty(), null, "structproperty", null, 0, 1, YStructRefPair.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYStructRefPair_Structclass(), theModelPackage.getYAnnotEntity(), null, "structclass", null, 0, 1, YStructRefPair.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(yJoinEClass, YJoin.class, "YJoin", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getYJoin_Joindefs(), this.getYJoinDef(), null, "joindefs", null, 0, -1, YJoin.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(yJoinDefEClass, YJoinDef.class, "YJoinDef", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getYJoinDef_FromView(), this.getYProperty(), null, "fromView", null, 0, 1, YJoinDef.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYJoinDef_RelRef(), theModelPackage.getYAnnotRelationship(), null, "relRef", null, 0, 1, YJoinDef.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYJoinDef_ToView(), this.getYProperty(), null, "toView", null, 0, 1, YJoinDef.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(yWhereEClass, YWhere.class, "YWhere", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getYWhere_Expression(), this.getYExpression(), null, "expression", null, 0, 1, YWhere.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(yWhileStatementEClass, YWhileStatement.class, "YWhileStatement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getYWhileStatement_Expression(), this.getYExpression(), null, "expression", null, 0, 1, YWhileStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYWhileStatement_Body(), this.getYBlock(), null, "body", null, 0, 1, YWhileStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(yRepeatWhileStatementEClass, YRepeatWhileStatement.class, "YRepeatWhileStatement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getYRepeatWhileStatement_Body(), this.getYBlock(), null, "body", null, 0, 1, YRepeatWhileStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYRepeatWhileStatement_Expression(), this.getYExpression(), null, "expression", null, 0, 1, YRepeatWhileStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(yForInStatementEClass, YForInStatement.class, "YForInStatement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getYForInStatement_Item(), this.getYProperty(), null, "item", null, 0, 1, YForInStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYForInStatement_Collection(), this.getYProperty(), null, "collection", null, 0, 1, YForInStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYForInStatement_Body(), this.getYBlock(), null, "body", null, 0, 1, YForInStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(yAssignmentEClass, YAssignment.class, "YAssignment", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getYAssignment_Left(), this.getYExpression(), null, "left", null, 0, 1, YAssignment.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYAssignment_Right(), this.getYExpression(), null, "right", null, 0, 1, YAssignment.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(yMemberSelectionEClass, YMemberSelection.class, "YMemberSelection", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getYMemberSelection_Receiver(), this.getYExpression(), null, "receiver", null, 0, 1, YMemberSelection.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYMemberSelection_Member(), this.getYMember(), null, "member", null, 0, 1, YMemberSelection.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getYMemberSelection_Functioninvocation(), ecorePackage.getEBoolean(), "functioninvocation", null, 0, 1, YMemberSelection.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYMemberSelection_Args(), this.getYExpression(), null, "args", null, 0, -1, YMemberSelection.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(yOrExpressionEClass, YOrExpression.class, "YOrExpression", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getYOrExpression_Left(), this.getYExpression(), null, "left", null, 0, 1, YOrExpression.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYOrExpression_Right(), this.getYExpression(), null, "right", null, 0, 1, YOrExpression.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(yAndExpressionEClass, YAndExpression.class, "YAndExpression", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getYAndExpression_Left(), this.getYExpression(), null, "left", null, 0, 1, YAndExpression.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYAndExpression_Right(), this.getYExpression(), null, "right", null, 0, 1, YAndExpression.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(yEqualityExpressionEClass, YEqualityExpression.class, "YEqualityExpression", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getYEqualityExpression_Left(), this.getYExpression(), null, "left", null, 0, 1, YEqualityExpression.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getYEqualityExpression_Op(), ecorePackage.getEString(), "op", null, 0, 1, YEqualityExpression.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYEqualityExpression_Right(), this.getYExpression(), null, "right", null, 0, 1, YEqualityExpression.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(yComparisonExpressionEClass, YComparisonExpression.class, "YComparisonExpression", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getYComparisonExpression_Left(), this.getYExpression(), null, "left", null, 0, 1, YComparisonExpression.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getYComparisonExpression_Op(), ecorePackage.getEString(), "op", null, 0, 1, YComparisonExpression.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYComparisonExpression_Right(), this.getYExpression(), null, "right", null, 0, 1, YComparisonExpression.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(yPlusEClass, YPlus.class, "YPlus", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getYPlus_Left(), this.getYExpression(), null, "left", null, 0, 1, YPlus.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYPlus_Right(), this.getYExpression(), null, "right", null, 0, 1, YPlus.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(yMinusEClass, YMinus.class, "YMinus", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getYMinus_Left(), this.getYExpression(), null, "left", null, 0, 1, YMinus.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYMinus_Right(), this.getYExpression(), null, "right", null, 0, 1, YMinus.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(yMulOrDivEClass, YMulOrDiv.class, "YMulOrDiv", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getYMulOrDiv_Left(), this.getYExpression(), null, "left", null, 0, 1, YMulOrDiv.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getYMulOrDiv_Op(), ecorePackage.getEString(), "op", null, 0, 1, YMulOrDiv.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYMulOrDiv_Right(), this.getYExpression(), null, "right", null, 0, 1, YMulOrDiv.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(yParentiesEClass, YParenties.class, "YParenties", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getYParenties_A(), this.getYExpression(), null, "a", null, 0, 1, YParenties.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(yNotEClass, YNot.class, "YNot", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getYNot_Expression(), this.getYExpression(), null, "expression", null, 0, 1, YNot.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(yStringConstantEClass, YStringConstant.class, "YStringConstant", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getYStringConstant_Value(), ecorePackage.getEString(), "value", null, 0, 1, YStringConstant.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(yIntConstantEClass, YIntConstant.class, "YIntConstant", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getYIntConstant_Value(), ecorePackage.getEInt(), "value", null, 0, 1, YIntConstant.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(yBoolConstantEClass, YBoolConstant.class, "YBoolConstant", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getYBoolConstant_Value(), ecorePackage.getEString(), "value", null, 0, 1, YBoolConstant.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(ySelfEClass, YSelf.class, "YSelf", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(ySuperEClass, YSuper.class, "YSuper", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(yNullEClass, YNull.class, "YNull", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(ySymbolRefEClass, YSymbolRef.class, "YSymbolRef", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getYSymbolRef_Symbol(), this.getYSymbol(), null, "symbol", null, 0, 1, YSymbolRef.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(yNewEClass, YNew.class, "YNew", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getYNew_Type(), this.getYClass(), null, "type", null, 0, 1, YNew.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYNew_Arguments(), this.getYExpression(), null, "arguments", null, 0, -1, YNew.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    // Initialize enums and add enum literals
    initEEnum(yAccessLevelEEnum, YAccessLevel.class, "YAccessLevel");
    addEEnumLiteral(yAccessLevelEEnum, YAccessLevel.PRIVATE);
    addEEnumLiteral(yAccessLevelEEnum, YAccessLevel.PROTECTED);
    addEEnumLiteral(yAccessLevelEEnum, YAccessLevel.PUBLIC);

    // Create resource
    createResource(eNS_URI);
  }

} //LangPackageImpl
