/**
 * generated by Xtext 2.21.0
 */
package eu.jgen.notes.dmw.lite.base.lang.impl;

import eu.jgen.notes.dmw.lite.base.lang.LangPackage;
import eu.jgen.notes.dmw.lite.base.lang.YProperty;
import eu.jgen.notes.dmw.lite.base.lang.YTuples;

import eu.jgen.notes.dmw.lite.mdl.model.YAnnotAttribute;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>YProperty</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link eu.jgen.notes.dmw.lite.base.lang.impl.YPropertyImpl#getTuples <em>Tuples</em>}</li>
 *   <li>{@link eu.jgen.notes.dmw.lite.base.lang.impl.YPropertyImpl#isOptional <em>Optional</em>}</li>
 *   <li>{@link eu.jgen.notes.dmw.lite.base.lang.impl.YPropertyImpl#getAttrRef <em>Attr Ref</em>}</li>
 * </ul>
 *
 * @generated
 */
public class YPropertyImpl extends YMemberImpl implements YProperty
{
  /**
   * The cached value of the '{@link #getTuples() <em>Tuples</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTuples()
   * @generated
   * @ordered
   */
  protected YTuples tuples;

  /**
   * The default value of the '{@link #isOptional() <em>Optional</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isOptional()
   * @generated
   * @ordered
   */
  protected static final boolean OPTIONAL_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isOptional() <em>Optional</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isOptional()
   * @generated
   * @ordered
   */
  protected boolean optional = OPTIONAL_EDEFAULT;

  /**
   * The cached value of the '{@link #getAttrRef() <em>Attr Ref</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAttrRef()
   * @generated
   * @ordered
   */
  protected YAnnotAttribute attrRef;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected YPropertyImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return LangPackage.Literals.YPROPERTY;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public YTuples getTuples()
  {
    return tuples;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetTuples(YTuples newTuples, NotificationChain msgs)
  {
    YTuples oldTuples = tuples;
    tuples = newTuples;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, LangPackage.YPROPERTY__TUPLES, oldTuples, newTuples);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTuples(YTuples newTuples)
  {
    if (newTuples != tuples)
    {
      NotificationChain msgs = null;
      if (tuples != null)
        msgs = ((InternalEObject)tuples).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - LangPackage.YPROPERTY__TUPLES, null, msgs);
      if (newTuples != null)
        msgs = ((InternalEObject)newTuples).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - LangPackage.YPROPERTY__TUPLES, null, msgs);
      msgs = basicSetTuples(newTuples, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LangPackage.YPROPERTY__TUPLES, newTuples, newTuples));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isOptional()
  {
    return optional;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setOptional(boolean newOptional)
  {
    boolean oldOptional = optional;
    optional = newOptional;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LangPackage.YPROPERTY__OPTIONAL, oldOptional, optional));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public YAnnotAttribute getAttrRef()
  {
    if (attrRef != null && attrRef.eIsProxy())
    {
      InternalEObject oldAttrRef = (InternalEObject)attrRef;
      attrRef = (YAnnotAttribute)eResolveProxy(oldAttrRef);
      if (attrRef != oldAttrRef)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, LangPackage.YPROPERTY__ATTR_REF, oldAttrRef, attrRef));
      }
    }
    return attrRef;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public YAnnotAttribute basicGetAttrRef()
  {
    return attrRef;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAttrRef(YAnnotAttribute newAttrRef)
  {
    YAnnotAttribute oldAttrRef = attrRef;
    attrRef = newAttrRef;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LangPackage.YPROPERTY__ATTR_REF, oldAttrRef, attrRef));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case LangPackage.YPROPERTY__TUPLES:
        return basicSetTuples(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case LangPackage.YPROPERTY__TUPLES:
        return getTuples();
      case LangPackage.YPROPERTY__OPTIONAL:
        return isOptional();
      case LangPackage.YPROPERTY__ATTR_REF:
        if (resolve) return getAttrRef();
        return basicGetAttrRef();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case LangPackage.YPROPERTY__TUPLES:
        setTuples((YTuples)newValue);
        return;
      case LangPackage.YPROPERTY__OPTIONAL:
        setOptional((Boolean)newValue);
        return;
      case LangPackage.YPROPERTY__ATTR_REF:
        setAttrRef((YAnnotAttribute)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case LangPackage.YPROPERTY__TUPLES:
        setTuples((YTuples)null);
        return;
      case LangPackage.YPROPERTY__OPTIONAL:
        setOptional(OPTIONAL_EDEFAULT);
        return;
      case LangPackage.YPROPERTY__ATTR_REF:
        setAttrRef((YAnnotAttribute)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case LangPackage.YPROPERTY__TUPLES:
        return tuples != null;
      case LangPackage.YPROPERTY__OPTIONAL:
        return optional != OPTIONAL_EDEFAULT;
      case LangPackage.YPROPERTY__ATTR_REF:
        return attrRef != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (optional: ");
    result.append(optional);
    result.append(')');
    return result.toString();
  }

} //YPropertyImpl
