/**
 * generated by Xtext 2.15.0
 */
package eu.jgen.notes.dmw.lite.mdl.model;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see eu.jgen.notes.dmw.lite.mdl.model.ModelFactory
 * @model kind="package"
 * @generated
 */
public interface ModelPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "model";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.jgen.eu/notes/dmw/lite/mdl/Model";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "model";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  ModelPackage eINSTANCE = eu.jgen.notes.dmw.lite.mdl.model.impl.ModelPackageImpl.init();

  /**
   * The meta object id for the '{@link eu.jgen.notes.dmw.lite.mdl.model.impl.YModelImpl <em>YModel</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see eu.jgen.notes.dmw.lite.mdl.model.impl.YModelImpl
   * @see eu.jgen.notes.dmw.lite.mdl.model.impl.ModelPackageImpl#getYModel()
   * @generated
   */
  int YMODEL = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int YMODEL__NAME = 0;

  /**
   * The feature id for the '<em><b>Imports</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int YMODEL__IMPORTS = 1;

  /**
   * The feature id for the '<em><b>Annotations</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int YMODEL__ANNOTATIONS = 2;

  /**
   * The number of structural features of the '<em>YModel</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int YMODEL_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link eu.jgen.notes.dmw.lite.mdl.model.impl.YImportImpl <em>YImport</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see eu.jgen.notes.dmw.lite.mdl.model.impl.YImportImpl
   * @see eu.jgen.notes.dmw.lite.mdl.model.impl.ModelPackageImpl#getYImport()
   * @generated
   */
  int YIMPORT = 1;

  /**
   * The feature id for the '<em><b>Imported Namespace</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int YIMPORT__IMPORTED_NAMESPACE = 0;

  /**
   * The number of structural features of the '<em>YImport</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int YIMPORT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotationImpl <em>YAnnotation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotationImpl
   * @see eu.jgen.notes.dmw.lite.mdl.model.impl.ModelPackageImpl#getYAnnotation()
   * @generated
   */
  int YANNOTATION = 2;

  /**
   * The number of structural features of the '<em>YAnnotation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int YANNOTATION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotEntityImpl <em>YAnnot Entity</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotEntityImpl
   * @see eu.jgen.notes.dmw.lite.mdl.model.impl.ModelPackageImpl#getYAnnotEntity()
   * @generated
   */
  int YANNOT_ENTITY = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int YANNOT_ENTITY__NAME = YANNOTATION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Element Value Pairs</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int YANNOT_ENTITY__ELEMENT_VALUE_PAIRS = YANNOTATION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Annotations</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int YANNOT_ENTITY__ANNOTATIONS = YANNOTATION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>YAnnot Entity</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int YANNOT_ENTITY_FEATURE_COUNT = YANNOTATION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotIdInnerImpl <em>YAnnot Id Inner</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotIdInnerImpl
   * @see eu.jgen.notes.dmw.lite.mdl.model.impl.ModelPackageImpl#getYAnnotIdInner()
   * @generated
   */
  int YANNOT_ID_INNER = 6;

  /**
   * The number of structural features of the '<em>YAnnot Id Inner</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int YANNOT_ID_INNER_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotAttributeImpl <em>YAnnot Attribute</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotAttributeImpl
   * @see eu.jgen.notes.dmw.lite.mdl.model.impl.ModelPackageImpl#getYAnnotAttribute()
   * @generated
   */
  int YANNOT_ATTRIBUTE = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int YANNOT_ATTRIBUTE__NAME = YANNOT_ID_INNER_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Optional</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int YANNOT_ATTRIBUTE__OPTIONAL = YANNOT_ID_INNER_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Element Value Pairs</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int YANNOT_ATTRIBUTE__ELEMENT_VALUE_PAIRS = YANNOT_ID_INNER_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>YAnnot Attribute</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int YANNOT_ATTRIBUTE_FEATURE_COUNT = YANNOT_ID_INNER_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotRelationshipImpl <em>YAnnot Relationship</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotRelationshipImpl
   * @see eu.jgen.notes.dmw.lite.mdl.model.impl.ModelPackageImpl#getYAnnotRelationship()
   * @generated
   */
  int YANNOT_RELATIONSHIP = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int YANNOT_RELATIONSHIP__NAME = YANNOT_ID_INNER_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Optional</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int YANNOT_RELATIONSHIP__OPTIONAL = YANNOT_ID_INNER_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Target</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int YANNOT_RELATIONSHIP__TARGET = YANNOT_ID_INNER_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Many</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int YANNOT_RELATIONSHIP__MANY = YANNOT_ID_INNER_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Element Value Pairs</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int YANNOT_RELATIONSHIP__ELEMENT_VALUE_PAIRS = YANNOT_ID_INNER_FEATURE_COUNT + 4;

  /**
   * The feature id for the '<em><b>Inverse</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int YANNOT_RELATIONSHIP__INVERSE = YANNOT_ID_INNER_FEATURE_COUNT + 5;

  /**
   * The number of structural features of the '<em>YAnnot Relationship</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int YANNOT_RELATIONSHIP_FEATURE_COUNT = YANNOT_ID_INNER_FEATURE_COUNT + 6;

  /**
   * The meta object id for the '{@link eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotEntityInnerImpl <em>YAnnot Entity Inner</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotEntityInnerImpl
   * @see eu.jgen.notes.dmw.lite.mdl.model.impl.ModelPackageImpl#getYAnnotEntityInner()
   * @generated
   */
  int YANNOT_ENTITY_INNER = 9;

  /**
   * The number of structural features of the '<em>YAnnot Entity Inner</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int YANNOT_ENTITY_INNER_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotIdentifierImpl <em>YAnnot Identifier</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotIdentifierImpl
   * @see eu.jgen.notes.dmw.lite.mdl.model.impl.ModelPackageImpl#getYAnnotIdentifier()
   * @generated
   */
  int YANNOT_IDENTIFIER = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int YANNOT_IDENTIFIER__NAME = YANNOT_ENTITY_INNER_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Annots</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int YANNOT_IDENTIFIER__ANNOTS = YANNOT_ENTITY_INNER_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>YAnnot Identifier</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int YANNOT_IDENTIFIER_FEATURE_COUNT = YANNOT_ENTITY_INNER_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotationElementValuePairImpl <em>YAnnotation Element Value Pair</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotationElementValuePairImpl
   * @see eu.jgen.notes.dmw.lite.mdl.model.impl.ModelPackageImpl#getYAnnotationElementValuePair()
   * @generated
   */
  int YANNOTATION_ELEMENT_VALUE_PAIR = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int YANNOTATION_ELEMENT_VALUE_PAIR__NAME = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int YANNOTATION_ELEMENT_VALUE_PAIR__VALUE = 1;

  /**
   * The number of structural features of the '<em>YAnnotation Element Value Pair</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int YANNOTATION_ELEMENT_VALUE_PAIR_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotExpressionImpl <em>YAnnot Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotExpressionImpl
   * @see eu.jgen.notes.dmw.lite.mdl.model.impl.ModelPackageImpl#getYAnnotExpression()
   * @generated
   */
  int YANNOT_EXPRESSION = 10;

  /**
   * The number of structural features of the '<em>YAnnot Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int YANNOT_EXPRESSION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotTechnicalDesignImpl <em>YAnnot Technical Design</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotTechnicalDesignImpl
   * @see eu.jgen.notes.dmw.lite.mdl.model.impl.ModelPackageImpl#getYAnnotTechnicalDesign()
   * @generated
   */
  int YANNOT_TECHNICAL_DESIGN = 11;

  /**
   * The feature id for the '<em><b>Database</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int YANNOT_TECHNICAL_DESIGN__DATABASE = YANNOTATION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Features</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int YANNOT_TECHNICAL_DESIGN__FEATURES = YANNOTATION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>YAnnot Technical Design</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int YANNOT_TECHNICAL_DESIGN_FEATURE_COUNT = YANNOTATION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotTableImpl <em>YAnnot Table</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotTableImpl
   * @see eu.jgen.notes.dmw.lite.mdl.model.impl.ModelPackageImpl#getYAnnotTable()
   * @generated
   */
  int YANNOT_TABLE = 12;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int YANNOT_TABLE__NAME = 0;

  /**
   * The feature id for the '<em><b>Entityref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int YANNOT_TABLE__ENTITYREF = 1;

  /**
   * The feature id for the '<em><b>Columns</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int YANNOT_TABLE__COLUMNS = 2;

  /**
   * The feature id for the '<em><b>Primarykey</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int YANNOT_TABLE__PRIMARYKEY = 3;

  /**
   * The feature id for the '<em><b>Foreignkeys</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int YANNOT_TABLE__FOREIGNKEYS = 4;

  /**
   * The number of structural features of the '<em>YAnnot Table</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int YANNOT_TABLE_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotColumnImpl <em>YAnnot Column</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotColumnImpl
   * @see eu.jgen.notes.dmw.lite.mdl.model.impl.ModelPackageImpl#getYAnnotColumn()
   * @generated
   */
  int YANNOT_COLUMN = 13;

  /**
   * The feature id for the '<em><b>Attrref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int YANNOT_COLUMN__ATTRREF = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int YANNOT_COLUMN__TYPE = 1;

  /**
   * The feature id for the '<em><b>Optional</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int YANNOT_COLUMN__OPTIONAL = 2;

  /**
   * The feature id for the '<em><b>Element Value Pairs</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int YANNOT_COLUMN__ELEMENT_VALUE_PAIRS = 3;

  /**
   * The number of structural features of the '<em>YAnnot Column</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int YANNOT_COLUMN_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotColumnLikeImpl <em>YAnnot Column Like</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotColumnLikeImpl
   * @see eu.jgen.notes.dmw.lite.mdl.model.impl.ModelPackageImpl#getYAnnotColumnLike()
   * @generated
   */
  int YANNOT_COLUMN_LIKE = 14;

  /**
   * The feature id for the '<em><b>Columnref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int YANNOT_COLUMN_LIKE__COLUMNREF = 0;

  /**
   * The number of structural features of the '<em>YAnnot Column Like</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int YANNOT_COLUMN_LIKE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotAbstractColumnImpl <em>YAnnot Abstract Column</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotAbstractColumnImpl
   * @see eu.jgen.notes.dmw.lite.mdl.model.impl.ModelPackageImpl#getYAnnotAbstractColumn()
   * @generated
   */
  int YANNOT_ABSTRACT_COLUMN = 15;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int YANNOT_ABSTRACT_COLUMN__NAME = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int YANNOT_ABSTRACT_COLUMN__TYPE = 1;

  /**
   * The number of structural features of the '<em>YAnnot Abstract Column</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int YANNOT_ABSTRACT_COLUMN_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotPrimaryKeyImpl <em>YAnnot Primary Key</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotPrimaryKeyImpl
   * @see eu.jgen.notes.dmw.lite.mdl.model.impl.ModelPackageImpl#getYAnnotPrimaryKey()
   * @generated
   */
  int YANNOT_PRIMARY_KEY = 16;

  /**
   * The feature id for the '<em><b>Columns</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int YANNOT_PRIMARY_KEY__COLUMNS = 0;

  /**
   * The number of structural features of the '<em>YAnnot Primary Key</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int YANNOT_PRIMARY_KEY_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotForeignKeyImpl <em>YAnnot Foreign Key</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotForeignKeyImpl
   * @see eu.jgen.notes.dmw.lite.mdl.model.impl.ModelPackageImpl#getYAnnotForeignKey()
   * @generated
   */
  int YANNOT_FOREIGN_KEY = 17;

  /**
   * The feature id for the '<em><b>Relationship</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int YANNOT_FOREIGN_KEY__RELATIONSHIP = 0;

  /**
   * The feature id for the '<em><b>Columns</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int YANNOT_FOREIGN_KEY__COLUMNS = 1;

  /**
   * The number of structural features of the '<em>YAnnot Foreign Key</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int YANNOT_FOREIGN_KEY_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotJavaImpl <em>YAnnot Java</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotJavaImpl
   * @see eu.jgen.notes.dmw.lite.mdl.model.impl.ModelPackageImpl#getYAnnotJava()
   * @generated
   */
  int YANNOT_JAVA = 18;

  /**
   * The feature id for the '<em><b>Database</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int YANNOT_JAVA__DATABASE = YANNOTATION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>YAnnot Java</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int YANNOT_JAVA_FEATURE_COUNT = YANNOTATION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotSwiftImpl <em>YAnnot Swift</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotSwiftImpl
   * @see eu.jgen.notes.dmw.lite.mdl.model.impl.ModelPackageImpl#getYAnnotSwift()
   * @generated
   */
  int YANNOT_SWIFT = 19;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int YANNOT_SWIFT__NAME = YANNOTATION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Database</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int YANNOT_SWIFT__DATABASE = YANNOTATION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>YAnnot Swift</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int YANNOT_SWIFT_FEATURE_COUNT = YANNOTATION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotDatabaseImpl <em>YAnnot Database</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotDatabaseImpl
   * @see eu.jgen.notes.dmw.lite.mdl.model.impl.ModelPackageImpl#getYAnnotDatabase()
   * @generated
   */
  int YANNOT_DATABASE = 20;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int YANNOT_DATABASE__NAME = YANNOTATION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>YAnnot Database</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int YANNOT_DATABASE_FEATURE_COUNT = YANNOTATION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotKeywordImpl <em>YAnnot Keyword</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotKeywordImpl
   * @see eu.jgen.notes.dmw.lite.mdl.model.impl.ModelPackageImpl#getYAnnotKeyword()
   * @generated
   */
  int YANNOT_KEYWORD = 21;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int YANNOT_KEYWORD__VALUE = YANNOT_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>YAnnot Keyword</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int YANNOT_KEYWORD_FEATURE_COUNT = YANNOT_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotStringConstantImpl <em>YAnnot String Constant</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotStringConstantImpl
   * @see eu.jgen.notes.dmw.lite.mdl.model.impl.ModelPackageImpl#getYAnnotStringConstant()
   * @generated
   */
  int YANNOT_STRING_CONSTANT = 22;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int YANNOT_STRING_CONSTANT__VALUE = YANNOT_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>YAnnot String Constant</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int YANNOT_STRING_CONSTANT_FEATURE_COUNT = YANNOT_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotNumberConstantImpl <em>YAnnot Number Constant</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotNumberConstantImpl
   * @see eu.jgen.notes.dmw.lite.mdl.model.impl.ModelPackageImpl#getYAnnotNumberConstant()
   * @generated
   */
  int YANNOT_NUMBER_CONSTANT = 23;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int YANNOT_NUMBER_CONSTANT__VALUE = YANNOT_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>YAnnot Number Constant</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int YANNOT_NUMBER_CONSTANT_FEATURE_COUNT = YANNOT_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotBoolConstantImpl <em>YAnnot Bool Constant</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotBoolConstantImpl
   * @see eu.jgen.notes.dmw.lite.mdl.model.impl.ModelPackageImpl#getYAnnotBoolConstant()
   * @generated
   */
  int YANNOT_BOOL_CONSTANT = 24;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int YANNOT_BOOL_CONSTANT__VALUE = YANNOT_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>YAnnot Bool Constant</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int YANNOT_BOOL_CONSTANT_FEATURE_COUNT = YANNOT_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotArrayImpl <em>YAnnot Array</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotArrayImpl
   * @see eu.jgen.notes.dmw.lite.mdl.model.impl.ModelPackageImpl#getYAnnotArray()
   * @generated
   */
  int YANNOT_ARRAY = 25;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int YANNOT_ARRAY__ELEMENTS = YANNOT_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>YAnnot Array</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int YANNOT_ARRAY_FEATURE_COUNT = YANNOT_EXPRESSION_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link eu.jgen.notes.dmw.lite.mdl.model.YModel <em>YModel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>YModel</em>'.
   * @see eu.jgen.notes.dmw.lite.mdl.model.YModel
   * @generated
   */
  EClass getYModel();

  /**
   * Returns the meta object for the attribute '{@link eu.jgen.notes.dmw.lite.mdl.model.YModel#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see eu.jgen.notes.dmw.lite.mdl.model.YModel#getName()
   * @see #getYModel()
   * @generated
   */
  EAttribute getYModel_Name();

  /**
   * Returns the meta object for the containment reference list '{@link eu.jgen.notes.dmw.lite.mdl.model.YModel#getImports <em>Imports</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Imports</em>'.
   * @see eu.jgen.notes.dmw.lite.mdl.model.YModel#getImports()
   * @see #getYModel()
   * @generated
   */
  EReference getYModel_Imports();

  /**
   * Returns the meta object for the containment reference list '{@link eu.jgen.notes.dmw.lite.mdl.model.YModel#getAnnotations <em>Annotations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Annotations</em>'.
   * @see eu.jgen.notes.dmw.lite.mdl.model.YModel#getAnnotations()
   * @see #getYModel()
   * @generated
   */
  EReference getYModel_Annotations();

  /**
   * Returns the meta object for class '{@link eu.jgen.notes.dmw.lite.mdl.model.YImport <em>YImport</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>YImport</em>'.
   * @see eu.jgen.notes.dmw.lite.mdl.model.YImport
   * @generated
   */
  EClass getYImport();

  /**
   * Returns the meta object for the attribute '{@link eu.jgen.notes.dmw.lite.mdl.model.YImport#getImportedNamespace <em>Imported Namespace</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Imported Namespace</em>'.
   * @see eu.jgen.notes.dmw.lite.mdl.model.YImport#getImportedNamespace()
   * @see #getYImport()
   * @generated
   */
  EAttribute getYImport_ImportedNamespace();

  /**
   * Returns the meta object for class '{@link eu.jgen.notes.dmw.lite.mdl.model.YAnnotation <em>YAnnotation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>YAnnotation</em>'.
   * @see eu.jgen.notes.dmw.lite.mdl.model.YAnnotation
   * @generated
   */
  EClass getYAnnotation();

  /**
   * Returns the meta object for class '{@link eu.jgen.notes.dmw.lite.mdl.model.YAnnotEntity <em>YAnnot Entity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>YAnnot Entity</em>'.
   * @see eu.jgen.notes.dmw.lite.mdl.model.YAnnotEntity
   * @generated
   */
  EClass getYAnnotEntity();

  /**
   * Returns the meta object for the attribute '{@link eu.jgen.notes.dmw.lite.mdl.model.YAnnotEntity#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see eu.jgen.notes.dmw.lite.mdl.model.YAnnotEntity#getName()
   * @see #getYAnnotEntity()
   * @generated
   */
  EAttribute getYAnnotEntity_Name();

  /**
   * Returns the meta object for the containment reference list '{@link eu.jgen.notes.dmw.lite.mdl.model.YAnnotEntity#getElementValuePairs <em>Element Value Pairs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Element Value Pairs</em>'.
   * @see eu.jgen.notes.dmw.lite.mdl.model.YAnnotEntity#getElementValuePairs()
   * @see #getYAnnotEntity()
   * @generated
   */
  EReference getYAnnotEntity_ElementValuePairs();

  /**
   * Returns the meta object for the containment reference list '{@link eu.jgen.notes.dmw.lite.mdl.model.YAnnotEntity#getAnnotations <em>Annotations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Annotations</em>'.
   * @see eu.jgen.notes.dmw.lite.mdl.model.YAnnotEntity#getAnnotations()
   * @see #getYAnnotEntity()
   * @generated
   */
  EReference getYAnnotEntity_Annotations();

  /**
   * Returns the meta object for class '{@link eu.jgen.notes.dmw.lite.mdl.model.YAnnotAttribute <em>YAnnot Attribute</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>YAnnot Attribute</em>'.
   * @see eu.jgen.notes.dmw.lite.mdl.model.YAnnotAttribute
   * @generated
   */
  EClass getYAnnotAttribute();

  /**
   * Returns the meta object for the attribute '{@link eu.jgen.notes.dmw.lite.mdl.model.YAnnotAttribute#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see eu.jgen.notes.dmw.lite.mdl.model.YAnnotAttribute#getName()
   * @see #getYAnnotAttribute()
   * @generated
   */
  EAttribute getYAnnotAttribute_Name();

  /**
   * Returns the meta object for the attribute '{@link eu.jgen.notes.dmw.lite.mdl.model.YAnnotAttribute#getOptional <em>Optional</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Optional</em>'.
   * @see eu.jgen.notes.dmw.lite.mdl.model.YAnnotAttribute#getOptional()
   * @see #getYAnnotAttribute()
   * @generated
   */
  EAttribute getYAnnotAttribute_Optional();

  /**
   * Returns the meta object for the containment reference list '{@link eu.jgen.notes.dmw.lite.mdl.model.YAnnotAttribute#getElementValuePairs <em>Element Value Pairs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Element Value Pairs</em>'.
   * @see eu.jgen.notes.dmw.lite.mdl.model.YAnnotAttribute#getElementValuePairs()
   * @see #getYAnnotAttribute()
   * @generated
   */
  EReference getYAnnotAttribute_ElementValuePairs();

  /**
   * Returns the meta object for class '{@link eu.jgen.notes.dmw.lite.mdl.model.YAnnotRelationship <em>YAnnot Relationship</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>YAnnot Relationship</em>'.
   * @see eu.jgen.notes.dmw.lite.mdl.model.YAnnotRelationship
   * @generated
   */
  EClass getYAnnotRelationship();

  /**
   * Returns the meta object for the attribute '{@link eu.jgen.notes.dmw.lite.mdl.model.YAnnotRelationship#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see eu.jgen.notes.dmw.lite.mdl.model.YAnnotRelationship#getName()
   * @see #getYAnnotRelationship()
   * @generated
   */
  EAttribute getYAnnotRelationship_Name();

  /**
   * Returns the meta object for the attribute '{@link eu.jgen.notes.dmw.lite.mdl.model.YAnnotRelationship#isOptional <em>Optional</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Optional</em>'.
   * @see eu.jgen.notes.dmw.lite.mdl.model.YAnnotRelationship#isOptional()
   * @see #getYAnnotRelationship()
   * @generated
   */
  EAttribute getYAnnotRelationship_Optional();

  /**
   * Returns the meta object for the reference '{@link eu.jgen.notes.dmw.lite.mdl.model.YAnnotRelationship#getTarget <em>Target</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Target</em>'.
   * @see eu.jgen.notes.dmw.lite.mdl.model.YAnnotRelationship#getTarget()
   * @see #getYAnnotRelationship()
   * @generated
   */
  EReference getYAnnotRelationship_Target();

  /**
   * Returns the meta object for the attribute '{@link eu.jgen.notes.dmw.lite.mdl.model.YAnnotRelationship#isMany <em>Many</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Many</em>'.
   * @see eu.jgen.notes.dmw.lite.mdl.model.YAnnotRelationship#isMany()
   * @see #getYAnnotRelationship()
   * @generated
   */
  EAttribute getYAnnotRelationship_Many();

  /**
   * Returns the meta object for the containment reference list '{@link eu.jgen.notes.dmw.lite.mdl.model.YAnnotRelationship#getElementValuePairs <em>Element Value Pairs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Element Value Pairs</em>'.
   * @see eu.jgen.notes.dmw.lite.mdl.model.YAnnotRelationship#getElementValuePairs()
   * @see #getYAnnotRelationship()
   * @generated
   */
  EReference getYAnnotRelationship_ElementValuePairs();

  /**
   * Returns the meta object for the reference '{@link eu.jgen.notes.dmw.lite.mdl.model.YAnnotRelationship#getInverse <em>Inverse</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Inverse</em>'.
   * @see eu.jgen.notes.dmw.lite.mdl.model.YAnnotRelationship#getInverse()
   * @see #getYAnnotRelationship()
   * @generated
   */
  EReference getYAnnotRelationship_Inverse();

  /**
   * Returns the meta object for class '{@link eu.jgen.notes.dmw.lite.mdl.model.YAnnotIdInner <em>YAnnot Id Inner</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>YAnnot Id Inner</em>'.
   * @see eu.jgen.notes.dmw.lite.mdl.model.YAnnotIdInner
   * @generated
   */
  EClass getYAnnotIdInner();

  /**
   * Returns the meta object for class '{@link eu.jgen.notes.dmw.lite.mdl.model.YAnnotIdentifier <em>YAnnot Identifier</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>YAnnot Identifier</em>'.
   * @see eu.jgen.notes.dmw.lite.mdl.model.YAnnotIdentifier
   * @generated
   */
  EClass getYAnnotIdentifier();

  /**
   * Returns the meta object for the attribute '{@link eu.jgen.notes.dmw.lite.mdl.model.YAnnotIdentifier#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see eu.jgen.notes.dmw.lite.mdl.model.YAnnotIdentifier#getName()
   * @see #getYAnnotIdentifier()
   * @generated
   */
  EAttribute getYAnnotIdentifier_Name();

  /**
   * Returns the meta object for the reference list '{@link eu.jgen.notes.dmw.lite.mdl.model.YAnnotIdentifier#getAnnots <em>Annots</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Annots</em>'.
   * @see eu.jgen.notes.dmw.lite.mdl.model.YAnnotIdentifier#getAnnots()
   * @see #getYAnnotIdentifier()
   * @generated
   */
  EReference getYAnnotIdentifier_Annots();

  /**
   * Returns the meta object for class '{@link eu.jgen.notes.dmw.lite.mdl.model.YAnnotationElementValuePair <em>YAnnotation Element Value Pair</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>YAnnotation Element Value Pair</em>'.
   * @see eu.jgen.notes.dmw.lite.mdl.model.YAnnotationElementValuePair
   * @generated
   */
  EClass getYAnnotationElementValuePair();

  /**
   * Returns the meta object for the attribute '{@link eu.jgen.notes.dmw.lite.mdl.model.YAnnotationElementValuePair#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see eu.jgen.notes.dmw.lite.mdl.model.YAnnotationElementValuePair#getName()
   * @see #getYAnnotationElementValuePair()
   * @generated
   */
  EAttribute getYAnnotationElementValuePair_Name();

  /**
   * Returns the meta object for the containment reference '{@link eu.jgen.notes.dmw.lite.mdl.model.YAnnotationElementValuePair#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see eu.jgen.notes.dmw.lite.mdl.model.YAnnotationElementValuePair#getValue()
   * @see #getYAnnotationElementValuePair()
   * @generated
   */
  EReference getYAnnotationElementValuePair_Value();

  /**
   * Returns the meta object for class '{@link eu.jgen.notes.dmw.lite.mdl.model.YAnnotEntityInner <em>YAnnot Entity Inner</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>YAnnot Entity Inner</em>'.
   * @see eu.jgen.notes.dmw.lite.mdl.model.YAnnotEntityInner
   * @generated
   */
  EClass getYAnnotEntityInner();

  /**
   * Returns the meta object for class '{@link eu.jgen.notes.dmw.lite.mdl.model.YAnnotExpression <em>YAnnot Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>YAnnot Expression</em>'.
   * @see eu.jgen.notes.dmw.lite.mdl.model.YAnnotExpression
   * @generated
   */
  EClass getYAnnotExpression();

  /**
   * Returns the meta object for class '{@link eu.jgen.notes.dmw.lite.mdl.model.YAnnotTechnicalDesign <em>YAnnot Technical Design</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>YAnnot Technical Design</em>'.
   * @see eu.jgen.notes.dmw.lite.mdl.model.YAnnotTechnicalDesign
   * @generated
   */
  EClass getYAnnotTechnicalDesign();

  /**
   * Returns the meta object for the reference '{@link eu.jgen.notes.dmw.lite.mdl.model.YAnnotTechnicalDesign#getDatabase <em>Database</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Database</em>'.
   * @see eu.jgen.notes.dmw.lite.mdl.model.YAnnotTechnicalDesign#getDatabase()
   * @see #getYAnnotTechnicalDesign()
   * @generated
   */
  EReference getYAnnotTechnicalDesign_Database();

  /**
   * Returns the meta object for the containment reference list '{@link eu.jgen.notes.dmw.lite.mdl.model.YAnnotTechnicalDesign#getFeatures <em>Features</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Features</em>'.
   * @see eu.jgen.notes.dmw.lite.mdl.model.YAnnotTechnicalDesign#getFeatures()
   * @see #getYAnnotTechnicalDesign()
   * @generated
   */
  EReference getYAnnotTechnicalDesign_Features();

  /**
   * Returns the meta object for class '{@link eu.jgen.notes.dmw.lite.mdl.model.YAnnotTable <em>YAnnot Table</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>YAnnot Table</em>'.
   * @see eu.jgen.notes.dmw.lite.mdl.model.YAnnotTable
   * @generated
   */
  EClass getYAnnotTable();

  /**
   * Returns the meta object for the attribute '{@link eu.jgen.notes.dmw.lite.mdl.model.YAnnotTable#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see eu.jgen.notes.dmw.lite.mdl.model.YAnnotTable#getName()
   * @see #getYAnnotTable()
   * @generated
   */
  EAttribute getYAnnotTable_Name();

  /**
   * Returns the meta object for the reference '{@link eu.jgen.notes.dmw.lite.mdl.model.YAnnotTable#getEntityref <em>Entityref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Entityref</em>'.
   * @see eu.jgen.notes.dmw.lite.mdl.model.YAnnotTable#getEntityref()
   * @see #getYAnnotTable()
   * @generated
   */
  EReference getYAnnotTable_Entityref();

  /**
   * Returns the meta object for the containment reference list '{@link eu.jgen.notes.dmw.lite.mdl.model.YAnnotTable#getColumns <em>Columns</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Columns</em>'.
   * @see eu.jgen.notes.dmw.lite.mdl.model.YAnnotTable#getColumns()
   * @see #getYAnnotTable()
   * @generated
   */
  EReference getYAnnotTable_Columns();

  /**
   * Returns the meta object for the containment reference '{@link eu.jgen.notes.dmw.lite.mdl.model.YAnnotTable#getPrimarykey <em>Primarykey</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Primarykey</em>'.
   * @see eu.jgen.notes.dmw.lite.mdl.model.YAnnotTable#getPrimarykey()
   * @see #getYAnnotTable()
   * @generated
   */
  EReference getYAnnotTable_Primarykey();

  /**
   * Returns the meta object for the containment reference list '{@link eu.jgen.notes.dmw.lite.mdl.model.YAnnotTable#getForeignkeys <em>Foreignkeys</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Foreignkeys</em>'.
   * @see eu.jgen.notes.dmw.lite.mdl.model.YAnnotTable#getForeignkeys()
   * @see #getYAnnotTable()
   * @generated
   */
  EReference getYAnnotTable_Foreignkeys();

  /**
   * Returns the meta object for class '{@link eu.jgen.notes.dmw.lite.mdl.model.YAnnotColumn <em>YAnnot Column</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>YAnnot Column</em>'.
   * @see eu.jgen.notes.dmw.lite.mdl.model.YAnnotColumn
   * @generated
   */
  EClass getYAnnotColumn();

  /**
   * Returns the meta object for the reference '{@link eu.jgen.notes.dmw.lite.mdl.model.YAnnotColumn#getAttrref <em>Attrref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Attrref</em>'.
   * @see eu.jgen.notes.dmw.lite.mdl.model.YAnnotColumn#getAttrref()
   * @see #getYAnnotColumn()
   * @generated
   */
  EReference getYAnnotColumn_Attrref();

  /**
   * Returns the meta object for the attribute '{@link eu.jgen.notes.dmw.lite.mdl.model.YAnnotColumn#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see eu.jgen.notes.dmw.lite.mdl.model.YAnnotColumn#getType()
   * @see #getYAnnotColumn()
   * @generated
   */
  EAttribute getYAnnotColumn_Type();

  /**
   * Returns the meta object for the attribute '{@link eu.jgen.notes.dmw.lite.mdl.model.YAnnotColumn#getOptional <em>Optional</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Optional</em>'.
   * @see eu.jgen.notes.dmw.lite.mdl.model.YAnnotColumn#getOptional()
   * @see #getYAnnotColumn()
   * @generated
   */
  EAttribute getYAnnotColumn_Optional();

  /**
   * Returns the meta object for the containment reference list '{@link eu.jgen.notes.dmw.lite.mdl.model.YAnnotColumn#getElementValuePairs <em>Element Value Pairs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Element Value Pairs</em>'.
   * @see eu.jgen.notes.dmw.lite.mdl.model.YAnnotColumn#getElementValuePairs()
   * @see #getYAnnotColumn()
   * @generated
   */
  EReference getYAnnotColumn_ElementValuePairs();

  /**
   * Returns the meta object for class '{@link eu.jgen.notes.dmw.lite.mdl.model.YAnnotColumnLike <em>YAnnot Column Like</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>YAnnot Column Like</em>'.
   * @see eu.jgen.notes.dmw.lite.mdl.model.YAnnotColumnLike
   * @generated
   */
  EClass getYAnnotColumnLike();

  /**
   * Returns the meta object for the reference '{@link eu.jgen.notes.dmw.lite.mdl.model.YAnnotColumnLike#getColumnref <em>Columnref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Columnref</em>'.
   * @see eu.jgen.notes.dmw.lite.mdl.model.YAnnotColumnLike#getColumnref()
   * @see #getYAnnotColumnLike()
   * @generated
   */
  EReference getYAnnotColumnLike_Columnref();

  /**
   * Returns the meta object for class '{@link eu.jgen.notes.dmw.lite.mdl.model.YAnnotAbstractColumn <em>YAnnot Abstract Column</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>YAnnot Abstract Column</em>'.
   * @see eu.jgen.notes.dmw.lite.mdl.model.YAnnotAbstractColumn
   * @generated
   */
  EClass getYAnnotAbstractColumn();

  /**
   * Returns the meta object for the attribute '{@link eu.jgen.notes.dmw.lite.mdl.model.YAnnotAbstractColumn#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see eu.jgen.notes.dmw.lite.mdl.model.YAnnotAbstractColumn#getName()
   * @see #getYAnnotAbstractColumn()
   * @generated
   */
  EAttribute getYAnnotAbstractColumn_Name();

  /**
   * Returns the meta object for the containment reference '{@link eu.jgen.notes.dmw.lite.mdl.model.YAnnotAbstractColumn#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see eu.jgen.notes.dmw.lite.mdl.model.YAnnotAbstractColumn#getType()
   * @see #getYAnnotAbstractColumn()
   * @generated
   */
  EReference getYAnnotAbstractColumn_Type();

  /**
   * Returns the meta object for class '{@link eu.jgen.notes.dmw.lite.mdl.model.YAnnotPrimaryKey <em>YAnnot Primary Key</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>YAnnot Primary Key</em>'.
   * @see eu.jgen.notes.dmw.lite.mdl.model.YAnnotPrimaryKey
   * @generated
   */
  EClass getYAnnotPrimaryKey();

  /**
   * Returns the meta object for the reference list '{@link eu.jgen.notes.dmw.lite.mdl.model.YAnnotPrimaryKey#getColumns <em>Columns</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Columns</em>'.
   * @see eu.jgen.notes.dmw.lite.mdl.model.YAnnotPrimaryKey#getColumns()
   * @see #getYAnnotPrimaryKey()
   * @generated
   */
  EReference getYAnnotPrimaryKey_Columns();

  /**
   * Returns the meta object for class '{@link eu.jgen.notes.dmw.lite.mdl.model.YAnnotForeignKey <em>YAnnot Foreign Key</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>YAnnot Foreign Key</em>'.
   * @see eu.jgen.notes.dmw.lite.mdl.model.YAnnotForeignKey
   * @generated
   */
  EClass getYAnnotForeignKey();

  /**
   * Returns the meta object for the reference '{@link eu.jgen.notes.dmw.lite.mdl.model.YAnnotForeignKey#getRelationship <em>Relationship</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Relationship</em>'.
   * @see eu.jgen.notes.dmw.lite.mdl.model.YAnnotForeignKey#getRelationship()
   * @see #getYAnnotForeignKey()
   * @generated
   */
  EReference getYAnnotForeignKey_Relationship();

  /**
   * Returns the meta object for the containment reference list '{@link eu.jgen.notes.dmw.lite.mdl.model.YAnnotForeignKey#getColumns <em>Columns</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Columns</em>'.
   * @see eu.jgen.notes.dmw.lite.mdl.model.YAnnotForeignKey#getColumns()
   * @see #getYAnnotForeignKey()
   * @generated
   */
  EReference getYAnnotForeignKey_Columns();

  /**
   * Returns the meta object for class '{@link eu.jgen.notes.dmw.lite.mdl.model.YAnnotJava <em>YAnnot Java</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>YAnnot Java</em>'.
   * @see eu.jgen.notes.dmw.lite.mdl.model.YAnnotJava
   * @generated
   */
  EClass getYAnnotJava();

  /**
   * Returns the meta object for the reference '{@link eu.jgen.notes.dmw.lite.mdl.model.YAnnotJava#getDatabase <em>Database</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Database</em>'.
   * @see eu.jgen.notes.dmw.lite.mdl.model.YAnnotJava#getDatabase()
   * @see #getYAnnotJava()
   * @generated
   */
  EReference getYAnnotJava_Database();

  /**
   * Returns the meta object for class '{@link eu.jgen.notes.dmw.lite.mdl.model.YAnnotSwift <em>YAnnot Swift</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>YAnnot Swift</em>'.
   * @see eu.jgen.notes.dmw.lite.mdl.model.YAnnotSwift
   * @generated
   */
  EClass getYAnnotSwift();

  /**
   * Returns the meta object for the attribute '{@link eu.jgen.notes.dmw.lite.mdl.model.YAnnotSwift#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see eu.jgen.notes.dmw.lite.mdl.model.YAnnotSwift#getName()
   * @see #getYAnnotSwift()
   * @generated
   */
  EAttribute getYAnnotSwift_Name();

  /**
   * Returns the meta object for the reference '{@link eu.jgen.notes.dmw.lite.mdl.model.YAnnotSwift#getDatabase <em>Database</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Database</em>'.
   * @see eu.jgen.notes.dmw.lite.mdl.model.YAnnotSwift#getDatabase()
   * @see #getYAnnotSwift()
   * @generated
   */
  EReference getYAnnotSwift_Database();

  /**
   * Returns the meta object for class '{@link eu.jgen.notes.dmw.lite.mdl.model.YAnnotDatabase <em>YAnnot Database</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>YAnnot Database</em>'.
   * @see eu.jgen.notes.dmw.lite.mdl.model.YAnnotDatabase
   * @generated
   */
  EClass getYAnnotDatabase();

  /**
   * Returns the meta object for the attribute '{@link eu.jgen.notes.dmw.lite.mdl.model.YAnnotDatabase#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see eu.jgen.notes.dmw.lite.mdl.model.YAnnotDatabase#getName()
   * @see #getYAnnotDatabase()
   * @generated
   */
  EAttribute getYAnnotDatabase_Name();

  /**
   * Returns the meta object for class '{@link eu.jgen.notes.dmw.lite.mdl.model.YAnnotKeyword <em>YAnnot Keyword</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>YAnnot Keyword</em>'.
   * @see eu.jgen.notes.dmw.lite.mdl.model.YAnnotKeyword
   * @generated
   */
  EClass getYAnnotKeyword();

  /**
   * Returns the meta object for the attribute '{@link eu.jgen.notes.dmw.lite.mdl.model.YAnnotKeyword#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see eu.jgen.notes.dmw.lite.mdl.model.YAnnotKeyword#getValue()
   * @see #getYAnnotKeyword()
   * @generated
   */
  EAttribute getYAnnotKeyword_Value();

  /**
   * Returns the meta object for class '{@link eu.jgen.notes.dmw.lite.mdl.model.YAnnotStringConstant <em>YAnnot String Constant</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>YAnnot String Constant</em>'.
   * @see eu.jgen.notes.dmw.lite.mdl.model.YAnnotStringConstant
   * @generated
   */
  EClass getYAnnotStringConstant();

  /**
   * Returns the meta object for the attribute '{@link eu.jgen.notes.dmw.lite.mdl.model.YAnnotStringConstant#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see eu.jgen.notes.dmw.lite.mdl.model.YAnnotStringConstant#getValue()
   * @see #getYAnnotStringConstant()
   * @generated
   */
  EAttribute getYAnnotStringConstant_Value();

  /**
   * Returns the meta object for class '{@link eu.jgen.notes.dmw.lite.mdl.model.YAnnotNumberConstant <em>YAnnot Number Constant</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>YAnnot Number Constant</em>'.
   * @see eu.jgen.notes.dmw.lite.mdl.model.YAnnotNumberConstant
   * @generated
   */
  EClass getYAnnotNumberConstant();

  /**
   * Returns the meta object for the attribute '{@link eu.jgen.notes.dmw.lite.mdl.model.YAnnotNumberConstant#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see eu.jgen.notes.dmw.lite.mdl.model.YAnnotNumberConstant#getValue()
   * @see #getYAnnotNumberConstant()
   * @generated
   */
  EAttribute getYAnnotNumberConstant_Value();

  /**
   * Returns the meta object for class '{@link eu.jgen.notes.dmw.lite.mdl.model.YAnnotBoolConstant <em>YAnnot Bool Constant</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>YAnnot Bool Constant</em>'.
   * @see eu.jgen.notes.dmw.lite.mdl.model.YAnnotBoolConstant
   * @generated
   */
  EClass getYAnnotBoolConstant();

  /**
   * Returns the meta object for the attribute '{@link eu.jgen.notes.dmw.lite.mdl.model.YAnnotBoolConstant#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see eu.jgen.notes.dmw.lite.mdl.model.YAnnotBoolConstant#getValue()
   * @see #getYAnnotBoolConstant()
   * @generated
   */
  EAttribute getYAnnotBoolConstant_Value();

  /**
   * Returns the meta object for class '{@link eu.jgen.notes.dmw.lite.mdl.model.YAnnotArray <em>YAnnot Array</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>YAnnot Array</em>'.
   * @see eu.jgen.notes.dmw.lite.mdl.model.YAnnotArray
   * @generated
   */
  EClass getYAnnotArray();

  /**
   * Returns the meta object for the containment reference list '{@link eu.jgen.notes.dmw.lite.mdl.model.YAnnotArray#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see eu.jgen.notes.dmw.lite.mdl.model.YAnnotArray#getElements()
   * @see #getYAnnotArray()
   * @generated
   */
  EReference getYAnnotArray_Elements();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  ModelFactory getModelFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link eu.jgen.notes.dmw.lite.mdl.model.impl.YModelImpl <em>YModel</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see eu.jgen.notes.dmw.lite.mdl.model.impl.YModelImpl
     * @see eu.jgen.notes.dmw.lite.mdl.model.impl.ModelPackageImpl#getYModel()
     * @generated
     */
    EClass YMODEL = eINSTANCE.getYModel();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute YMODEL__NAME = eINSTANCE.getYModel_Name();

    /**
     * The meta object literal for the '<em><b>Imports</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference YMODEL__IMPORTS = eINSTANCE.getYModel_Imports();

    /**
     * The meta object literal for the '<em><b>Annotations</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference YMODEL__ANNOTATIONS = eINSTANCE.getYModel_Annotations();

    /**
     * The meta object literal for the '{@link eu.jgen.notes.dmw.lite.mdl.model.impl.YImportImpl <em>YImport</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see eu.jgen.notes.dmw.lite.mdl.model.impl.YImportImpl
     * @see eu.jgen.notes.dmw.lite.mdl.model.impl.ModelPackageImpl#getYImport()
     * @generated
     */
    EClass YIMPORT = eINSTANCE.getYImport();

    /**
     * The meta object literal for the '<em><b>Imported Namespace</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute YIMPORT__IMPORTED_NAMESPACE = eINSTANCE.getYImport_ImportedNamespace();

    /**
     * The meta object literal for the '{@link eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotationImpl <em>YAnnotation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotationImpl
     * @see eu.jgen.notes.dmw.lite.mdl.model.impl.ModelPackageImpl#getYAnnotation()
     * @generated
     */
    EClass YANNOTATION = eINSTANCE.getYAnnotation();

    /**
     * The meta object literal for the '{@link eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotEntityImpl <em>YAnnot Entity</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotEntityImpl
     * @see eu.jgen.notes.dmw.lite.mdl.model.impl.ModelPackageImpl#getYAnnotEntity()
     * @generated
     */
    EClass YANNOT_ENTITY = eINSTANCE.getYAnnotEntity();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute YANNOT_ENTITY__NAME = eINSTANCE.getYAnnotEntity_Name();

    /**
     * The meta object literal for the '<em><b>Element Value Pairs</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference YANNOT_ENTITY__ELEMENT_VALUE_PAIRS = eINSTANCE.getYAnnotEntity_ElementValuePairs();

    /**
     * The meta object literal for the '<em><b>Annotations</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference YANNOT_ENTITY__ANNOTATIONS = eINSTANCE.getYAnnotEntity_Annotations();

    /**
     * The meta object literal for the '{@link eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotAttributeImpl <em>YAnnot Attribute</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotAttributeImpl
     * @see eu.jgen.notes.dmw.lite.mdl.model.impl.ModelPackageImpl#getYAnnotAttribute()
     * @generated
     */
    EClass YANNOT_ATTRIBUTE = eINSTANCE.getYAnnotAttribute();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute YANNOT_ATTRIBUTE__NAME = eINSTANCE.getYAnnotAttribute_Name();

    /**
     * The meta object literal for the '<em><b>Optional</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute YANNOT_ATTRIBUTE__OPTIONAL = eINSTANCE.getYAnnotAttribute_Optional();

    /**
     * The meta object literal for the '<em><b>Element Value Pairs</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference YANNOT_ATTRIBUTE__ELEMENT_VALUE_PAIRS = eINSTANCE.getYAnnotAttribute_ElementValuePairs();

    /**
     * The meta object literal for the '{@link eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotRelationshipImpl <em>YAnnot Relationship</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotRelationshipImpl
     * @see eu.jgen.notes.dmw.lite.mdl.model.impl.ModelPackageImpl#getYAnnotRelationship()
     * @generated
     */
    EClass YANNOT_RELATIONSHIP = eINSTANCE.getYAnnotRelationship();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute YANNOT_RELATIONSHIP__NAME = eINSTANCE.getYAnnotRelationship_Name();

    /**
     * The meta object literal for the '<em><b>Optional</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute YANNOT_RELATIONSHIP__OPTIONAL = eINSTANCE.getYAnnotRelationship_Optional();

    /**
     * The meta object literal for the '<em><b>Target</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference YANNOT_RELATIONSHIP__TARGET = eINSTANCE.getYAnnotRelationship_Target();

    /**
     * The meta object literal for the '<em><b>Many</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute YANNOT_RELATIONSHIP__MANY = eINSTANCE.getYAnnotRelationship_Many();

    /**
     * The meta object literal for the '<em><b>Element Value Pairs</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference YANNOT_RELATIONSHIP__ELEMENT_VALUE_PAIRS = eINSTANCE.getYAnnotRelationship_ElementValuePairs();

    /**
     * The meta object literal for the '<em><b>Inverse</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference YANNOT_RELATIONSHIP__INVERSE = eINSTANCE.getYAnnotRelationship_Inverse();

    /**
     * The meta object literal for the '{@link eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotIdInnerImpl <em>YAnnot Id Inner</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotIdInnerImpl
     * @see eu.jgen.notes.dmw.lite.mdl.model.impl.ModelPackageImpl#getYAnnotIdInner()
     * @generated
     */
    EClass YANNOT_ID_INNER = eINSTANCE.getYAnnotIdInner();

    /**
     * The meta object literal for the '{@link eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotIdentifierImpl <em>YAnnot Identifier</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotIdentifierImpl
     * @see eu.jgen.notes.dmw.lite.mdl.model.impl.ModelPackageImpl#getYAnnotIdentifier()
     * @generated
     */
    EClass YANNOT_IDENTIFIER = eINSTANCE.getYAnnotIdentifier();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute YANNOT_IDENTIFIER__NAME = eINSTANCE.getYAnnotIdentifier_Name();

    /**
     * The meta object literal for the '<em><b>Annots</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference YANNOT_IDENTIFIER__ANNOTS = eINSTANCE.getYAnnotIdentifier_Annots();

    /**
     * The meta object literal for the '{@link eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotationElementValuePairImpl <em>YAnnotation Element Value Pair</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotationElementValuePairImpl
     * @see eu.jgen.notes.dmw.lite.mdl.model.impl.ModelPackageImpl#getYAnnotationElementValuePair()
     * @generated
     */
    EClass YANNOTATION_ELEMENT_VALUE_PAIR = eINSTANCE.getYAnnotationElementValuePair();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute YANNOTATION_ELEMENT_VALUE_PAIR__NAME = eINSTANCE.getYAnnotationElementValuePair_Name();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference YANNOTATION_ELEMENT_VALUE_PAIR__VALUE = eINSTANCE.getYAnnotationElementValuePair_Value();

    /**
     * The meta object literal for the '{@link eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotEntityInnerImpl <em>YAnnot Entity Inner</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotEntityInnerImpl
     * @see eu.jgen.notes.dmw.lite.mdl.model.impl.ModelPackageImpl#getYAnnotEntityInner()
     * @generated
     */
    EClass YANNOT_ENTITY_INNER = eINSTANCE.getYAnnotEntityInner();

    /**
     * The meta object literal for the '{@link eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotExpressionImpl <em>YAnnot Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotExpressionImpl
     * @see eu.jgen.notes.dmw.lite.mdl.model.impl.ModelPackageImpl#getYAnnotExpression()
     * @generated
     */
    EClass YANNOT_EXPRESSION = eINSTANCE.getYAnnotExpression();

    /**
     * The meta object literal for the '{@link eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotTechnicalDesignImpl <em>YAnnot Technical Design</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotTechnicalDesignImpl
     * @see eu.jgen.notes.dmw.lite.mdl.model.impl.ModelPackageImpl#getYAnnotTechnicalDesign()
     * @generated
     */
    EClass YANNOT_TECHNICAL_DESIGN = eINSTANCE.getYAnnotTechnicalDesign();

    /**
     * The meta object literal for the '<em><b>Database</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference YANNOT_TECHNICAL_DESIGN__DATABASE = eINSTANCE.getYAnnotTechnicalDesign_Database();

    /**
     * The meta object literal for the '<em><b>Features</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference YANNOT_TECHNICAL_DESIGN__FEATURES = eINSTANCE.getYAnnotTechnicalDesign_Features();

    /**
     * The meta object literal for the '{@link eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotTableImpl <em>YAnnot Table</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotTableImpl
     * @see eu.jgen.notes.dmw.lite.mdl.model.impl.ModelPackageImpl#getYAnnotTable()
     * @generated
     */
    EClass YANNOT_TABLE = eINSTANCE.getYAnnotTable();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute YANNOT_TABLE__NAME = eINSTANCE.getYAnnotTable_Name();

    /**
     * The meta object literal for the '<em><b>Entityref</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference YANNOT_TABLE__ENTITYREF = eINSTANCE.getYAnnotTable_Entityref();

    /**
     * The meta object literal for the '<em><b>Columns</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference YANNOT_TABLE__COLUMNS = eINSTANCE.getYAnnotTable_Columns();

    /**
     * The meta object literal for the '<em><b>Primarykey</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference YANNOT_TABLE__PRIMARYKEY = eINSTANCE.getYAnnotTable_Primarykey();

    /**
     * The meta object literal for the '<em><b>Foreignkeys</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference YANNOT_TABLE__FOREIGNKEYS = eINSTANCE.getYAnnotTable_Foreignkeys();

    /**
     * The meta object literal for the '{@link eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotColumnImpl <em>YAnnot Column</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotColumnImpl
     * @see eu.jgen.notes.dmw.lite.mdl.model.impl.ModelPackageImpl#getYAnnotColumn()
     * @generated
     */
    EClass YANNOT_COLUMN = eINSTANCE.getYAnnotColumn();

    /**
     * The meta object literal for the '<em><b>Attrref</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference YANNOT_COLUMN__ATTRREF = eINSTANCE.getYAnnotColumn_Attrref();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute YANNOT_COLUMN__TYPE = eINSTANCE.getYAnnotColumn_Type();

    /**
     * The meta object literal for the '<em><b>Optional</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute YANNOT_COLUMN__OPTIONAL = eINSTANCE.getYAnnotColumn_Optional();

    /**
     * The meta object literal for the '<em><b>Element Value Pairs</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference YANNOT_COLUMN__ELEMENT_VALUE_PAIRS = eINSTANCE.getYAnnotColumn_ElementValuePairs();

    /**
     * The meta object literal for the '{@link eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotColumnLikeImpl <em>YAnnot Column Like</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotColumnLikeImpl
     * @see eu.jgen.notes.dmw.lite.mdl.model.impl.ModelPackageImpl#getYAnnotColumnLike()
     * @generated
     */
    EClass YANNOT_COLUMN_LIKE = eINSTANCE.getYAnnotColumnLike();

    /**
     * The meta object literal for the '<em><b>Columnref</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference YANNOT_COLUMN_LIKE__COLUMNREF = eINSTANCE.getYAnnotColumnLike_Columnref();

    /**
     * The meta object literal for the '{@link eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotAbstractColumnImpl <em>YAnnot Abstract Column</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotAbstractColumnImpl
     * @see eu.jgen.notes.dmw.lite.mdl.model.impl.ModelPackageImpl#getYAnnotAbstractColumn()
     * @generated
     */
    EClass YANNOT_ABSTRACT_COLUMN = eINSTANCE.getYAnnotAbstractColumn();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute YANNOT_ABSTRACT_COLUMN__NAME = eINSTANCE.getYAnnotAbstractColumn_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference YANNOT_ABSTRACT_COLUMN__TYPE = eINSTANCE.getYAnnotAbstractColumn_Type();

    /**
     * The meta object literal for the '{@link eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotPrimaryKeyImpl <em>YAnnot Primary Key</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotPrimaryKeyImpl
     * @see eu.jgen.notes.dmw.lite.mdl.model.impl.ModelPackageImpl#getYAnnotPrimaryKey()
     * @generated
     */
    EClass YANNOT_PRIMARY_KEY = eINSTANCE.getYAnnotPrimaryKey();

    /**
     * The meta object literal for the '<em><b>Columns</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference YANNOT_PRIMARY_KEY__COLUMNS = eINSTANCE.getYAnnotPrimaryKey_Columns();

    /**
     * The meta object literal for the '{@link eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotForeignKeyImpl <em>YAnnot Foreign Key</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotForeignKeyImpl
     * @see eu.jgen.notes.dmw.lite.mdl.model.impl.ModelPackageImpl#getYAnnotForeignKey()
     * @generated
     */
    EClass YANNOT_FOREIGN_KEY = eINSTANCE.getYAnnotForeignKey();

    /**
     * The meta object literal for the '<em><b>Relationship</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference YANNOT_FOREIGN_KEY__RELATIONSHIP = eINSTANCE.getYAnnotForeignKey_Relationship();

    /**
     * The meta object literal for the '<em><b>Columns</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference YANNOT_FOREIGN_KEY__COLUMNS = eINSTANCE.getYAnnotForeignKey_Columns();

    /**
     * The meta object literal for the '{@link eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotJavaImpl <em>YAnnot Java</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotJavaImpl
     * @see eu.jgen.notes.dmw.lite.mdl.model.impl.ModelPackageImpl#getYAnnotJava()
     * @generated
     */
    EClass YANNOT_JAVA = eINSTANCE.getYAnnotJava();

    /**
     * The meta object literal for the '<em><b>Database</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference YANNOT_JAVA__DATABASE = eINSTANCE.getYAnnotJava_Database();

    /**
     * The meta object literal for the '{@link eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotSwiftImpl <em>YAnnot Swift</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotSwiftImpl
     * @see eu.jgen.notes.dmw.lite.mdl.model.impl.ModelPackageImpl#getYAnnotSwift()
     * @generated
     */
    EClass YANNOT_SWIFT = eINSTANCE.getYAnnotSwift();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute YANNOT_SWIFT__NAME = eINSTANCE.getYAnnotSwift_Name();

    /**
     * The meta object literal for the '<em><b>Database</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference YANNOT_SWIFT__DATABASE = eINSTANCE.getYAnnotSwift_Database();

    /**
     * The meta object literal for the '{@link eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotDatabaseImpl <em>YAnnot Database</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotDatabaseImpl
     * @see eu.jgen.notes.dmw.lite.mdl.model.impl.ModelPackageImpl#getYAnnotDatabase()
     * @generated
     */
    EClass YANNOT_DATABASE = eINSTANCE.getYAnnotDatabase();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute YANNOT_DATABASE__NAME = eINSTANCE.getYAnnotDatabase_Name();

    /**
     * The meta object literal for the '{@link eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotKeywordImpl <em>YAnnot Keyword</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotKeywordImpl
     * @see eu.jgen.notes.dmw.lite.mdl.model.impl.ModelPackageImpl#getYAnnotKeyword()
     * @generated
     */
    EClass YANNOT_KEYWORD = eINSTANCE.getYAnnotKeyword();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute YANNOT_KEYWORD__VALUE = eINSTANCE.getYAnnotKeyword_Value();

    /**
     * The meta object literal for the '{@link eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotStringConstantImpl <em>YAnnot String Constant</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotStringConstantImpl
     * @see eu.jgen.notes.dmw.lite.mdl.model.impl.ModelPackageImpl#getYAnnotStringConstant()
     * @generated
     */
    EClass YANNOT_STRING_CONSTANT = eINSTANCE.getYAnnotStringConstant();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute YANNOT_STRING_CONSTANT__VALUE = eINSTANCE.getYAnnotStringConstant_Value();

    /**
     * The meta object literal for the '{@link eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotNumberConstantImpl <em>YAnnot Number Constant</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotNumberConstantImpl
     * @see eu.jgen.notes.dmw.lite.mdl.model.impl.ModelPackageImpl#getYAnnotNumberConstant()
     * @generated
     */
    EClass YANNOT_NUMBER_CONSTANT = eINSTANCE.getYAnnotNumberConstant();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute YANNOT_NUMBER_CONSTANT__VALUE = eINSTANCE.getYAnnotNumberConstant_Value();

    /**
     * The meta object literal for the '{@link eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotBoolConstantImpl <em>YAnnot Bool Constant</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotBoolConstantImpl
     * @see eu.jgen.notes.dmw.lite.mdl.model.impl.ModelPackageImpl#getYAnnotBoolConstant()
     * @generated
     */
    EClass YANNOT_BOOL_CONSTANT = eINSTANCE.getYAnnotBoolConstant();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute YANNOT_BOOL_CONSTANT__VALUE = eINSTANCE.getYAnnotBoolConstant_Value();

    /**
     * The meta object literal for the '{@link eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotArrayImpl <em>YAnnot Array</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see eu.jgen.notes.dmw.lite.mdl.model.impl.YAnnotArrayImpl
     * @see eu.jgen.notes.dmw.lite.mdl.model.impl.ModelPackageImpl#getYAnnotArray()
     * @generated
     */
    EClass YANNOT_ARRAY = eINSTANCE.getYAnnotArray();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference YANNOT_ARRAY__ELEMENTS = eINSTANCE.getYAnnotArray_Elements();

  }

} //ModelPackage
