/**
 * generated by Xtext 2.21.0
 */
package eu.jgen.notes.dmw.lite.mdl.model;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>YAnnot Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see eu.jgen.notes.dmw.lite.mdl.model.ModelPackage#getYAnnotExpression()
 * @model
 * @generated
 */
public interface YAnnotExpression extends EObject
{
} // YAnnotExpression
