/**
 * generated by Xtext 2.15.0
 */
package eu.jgen.notes.dmw.lite.mdl.ui;

import eu.jgen.notes.dmw.lite.mdl.ui.AbstractModelUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class ModelUiModule extends AbstractModelUiModule {
  public ModelUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
