/**
 * generated by Xtext 2.21.0
 */
package eu.jgen.notes.dmw.lite.base.lang;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see eu.jgen.notes.dmw.lite.base.lang.LangPackage
 * @generated
 */
public interface LangFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  LangFactory eINSTANCE = eu.jgen.notes.dmw.lite.base.lang.impl.LangFactoryImpl.init();

  /**
   * Returns a new object of class '<em>YWidget</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>YWidget</em>'.
   * @generated
   */
  YWidget createYWidget();

  /**
   * Returns a new object of class '<em>YParameter</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>YParameter</em>'.
   * @generated
   */
  YParameter createYParameter();

  /**
   * Returns a new object of class '<em>YArgument</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>YArgument</em>'.
   * @generated
   */
  YArgument createYArgument();

  /**
   * Returns a new object of class '<em>YEnumeration</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>YEnumeration</em>'.
   * @generated
   */
  YEnumeration createYEnumeration();

  /**
   * Returns a new object of class '<em>YEnumeration Case</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>YEnumeration Case</em>'.
   * @generated
   */
  YEnumerationCase createYEnumerationCase();

  /**
   * Returns a new object of class '<em>YClass</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>YClass</em>'.
   * @generated
   */
  YClass createYClass();

  /**
   * Returns a new object of class '<em>YMember</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>YMember</em>'.
   * @generated
   */
  YMember createYMember();

  /**
   * Returns a new object of class '<em>YProperty</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>YProperty</em>'.
   * @generated
   */
  YProperty createYProperty();

  /**
   * Returns a new object of class '<em>YTuples</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>YTuples</em>'.
   * @generated
   */
  YTuples createYTuples();

  /**
   * Returns a new object of class '<em>YFunction</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>YFunction</em>'.
   * @generated
   */
  YFunction createYFunction();

  /**
   * Returns a new object of class '<em>YBlock</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>YBlock</em>'.
   * @generated
   */
  YBlock createYBlock();

  /**
   * Returns a new object of class '<em>YStatement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>YStatement</em>'.
   * @generated
   */
  YStatement createYStatement();

  /**
   * Returns a new object of class '<em>YDo Statement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>YDo Statement</em>'.
   * @generated
   */
  YDoStatement createYDoStatement();

  /**
   * Returns a new object of class '<em>YCatch</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>YCatch</em>'.
   * @generated
   */
  YCatch createYCatch();

  /**
   * Returns a new object of class '<em>YCatch Block</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>YCatch Block</em>'.
   * @generated
   */
  YCatchBlock createYCatchBlock();

  /**
   * Returns a new object of class '<em>YVariable Declaration</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>YVariable Declaration</em>'.
   * @generated
   */
  YVariableDeclaration createYVariableDeclaration();

  /**
   * Returns a new object of class '<em>YThrow</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>YThrow</em>'.
   * @generated
   */
  YThrow createYThrow();

  /**
   * Returns a new object of class '<em>YReturn</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>YReturn</em>'.
   * @generated
   */
  YReturn createYReturn();

  /**
   * Returns a new object of class '<em>YIf Statement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>YIf Statement</em>'.
   * @generated
   */
  YIfStatement createYIfStatement();

  /**
   * Returns a new object of class '<em>YSwitch Statement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>YSwitch Statement</em>'.
   * @generated
   */
  YSwitchStatement createYSwitchStatement();

  /**
   * Returns a new object of class '<em>YSwitch Case</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>YSwitch Case</em>'.
   * @generated
   */
  YSwitchCase createYSwitchCase();

  /**
   * Returns a new object of class '<em>YSymbol</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>YSymbol</em>'.
   * @generated
   */
  YSymbol createYSymbol();

  /**
   * Returns a new object of class '<em>YNamed Element</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>YNamed Element</em>'.
   * @generated
   */
  YNamedElement createYNamedElement();

  /**
   * Returns a new object of class '<em>YExpression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>YExpression</em>'.
   * @generated
   */
  YExpression createYExpression();

  /**
   * Returns a new object of class '<em>YRead Statement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>YRead Statement</em>'.
   * @generated
   */
  YReadStatement createYReadStatement();

  /**
   * Returns a new object of class '<em>YRead Each Statement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>YRead Each Statement</em>'.
   * @generated
   */
  YReadEachStatement createYReadEachStatement();

  /**
   * Returns a new object of class '<em>YCreate Statement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>YCreate Statement</em>'.
   * @generated
   */
  YCreateStatement createYCreateStatement();

  /**
   * Returns a new object of class '<em>YUpdate Statement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>YUpdate Statement</em>'.
   * @generated
   */
  YUpdateStatement createYUpdateStatement();

  /**
   * Returns a new object of class '<em>YDelete Statement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>YDelete Statement</em>'.
   * @generated
   */
  YDeleteStatement createYDeleteStatement();

  /**
   * Returns a new object of class '<em>YAssociate Statement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>YAssociate Statement</em>'.
   * @generated
   */
  YAssociateStatement createYAssociateStatement();

  /**
   * Returns a new object of class '<em>YDisassociate Statement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>YDisassociate Statement</em>'.
   * @generated
   */
  YDisassociateStatement createYDisassociateStatement();

  /**
   * Returns a new object of class '<em>YStruct Ref Pair</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>YStruct Ref Pair</em>'.
   * @generated
   */
  YStructRefPair createYStructRefPair();

  /**
   * Returns a new object of class '<em>YJoin</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>YJoin</em>'.
   * @generated
   */
  YJoin createYJoin();

  /**
   * Returns a new object of class '<em>YJoin Def</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>YJoin Def</em>'.
   * @generated
   */
  YJoinDef createYJoinDef();

  /**
   * Returns a new object of class '<em>YWhere</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>YWhere</em>'.
   * @generated
   */
  YWhere createYWhere();

  /**
   * Returns a new object of class '<em>YWhile Statement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>YWhile Statement</em>'.
   * @generated
   */
  YWhileStatement createYWhileStatement();

  /**
   * Returns a new object of class '<em>YRepeat While Statement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>YRepeat While Statement</em>'.
   * @generated
   */
  YRepeatWhileStatement createYRepeatWhileStatement();

  /**
   * Returns a new object of class '<em>YFor In Statement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>YFor In Statement</em>'.
   * @generated
   */
  YForInStatement createYForInStatement();

  /**
   * Returns a new object of class '<em>YAssignment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>YAssignment</em>'.
   * @generated
   */
  YAssignment createYAssignment();

  /**
   * Returns a new object of class '<em>YMember Selection</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>YMember Selection</em>'.
   * @generated
   */
  YMemberSelection createYMemberSelection();

  /**
   * Returns a new object of class '<em>YOr Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>YOr Expression</em>'.
   * @generated
   */
  YOrExpression createYOrExpression();

  /**
   * Returns a new object of class '<em>YAnd Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>YAnd Expression</em>'.
   * @generated
   */
  YAndExpression createYAndExpression();

  /**
   * Returns a new object of class '<em>YEquality Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>YEquality Expression</em>'.
   * @generated
   */
  YEqualityExpression createYEqualityExpression();

  /**
   * Returns a new object of class '<em>YComparison Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>YComparison Expression</em>'.
   * @generated
   */
  YComparisonExpression createYComparisonExpression();

  /**
   * Returns a new object of class '<em>YPlus</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>YPlus</em>'.
   * @generated
   */
  YPlus createYPlus();

  /**
   * Returns a new object of class '<em>YMinus</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>YMinus</em>'.
   * @generated
   */
  YMinus createYMinus();

  /**
   * Returns a new object of class '<em>YMul Or Div</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>YMul Or Div</em>'.
   * @generated
   */
  YMulOrDiv createYMulOrDiv();

  /**
   * Returns a new object of class '<em>YParenties</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>YParenties</em>'.
   * @generated
   */
  YParenties createYParenties();

  /**
   * Returns a new object of class '<em>YNot</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>YNot</em>'.
   * @generated
   */
  YNot createYNot();

  /**
   * Returns a new object of class '<em>YString Constant</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>YString Constant</em>'.
   * @generated
   */
  YStringConstant createYStringConstant();

  /**
   * Returns a new object of class '<em>YInt Constant</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>YInt Constant</em>'.
   * @generated
   */
  YIntConstant createYIntConstant();

  /**
   * Returns a new object of class '<em>YBool Constant</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>YBool Constant</em>'.
   * @generated
   */
  YBoolConstant createYBoolConstant();

  /**
   * Returns a new object of class '<em>YSelf</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>YSelf</em>'.
   * @generated
   */
  YSelf createYSelf();

  /**
   * Returns a new object of class '<em>YSuper</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>YSuper</em>'.
   * @generated
   */
  YSuper createYSuper();

  /**
   * Returns a new object of class '<em>YNull</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>YNull</em>'.
   * @generated
   */
  YNull createYNull();

  /**
   * Returns a new object of class '<em>YSymbol Ref</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>YSymbol Ref</em>'.
   * @generated
   */
  YSymbolRef createYSymbolRef();

  /**
   * Returns a new object of class '<em>YNew</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>YNew</em>'.
   * @generated
   */
  YNew createYNew();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  LangPackage getLangPackage();

} //LangFactory
