/**
 * generated by Xtext 2.15.0
 */
package eu.jgen.notes.dmw.lite.base.lang;

import eu.jgen.notes.dmw.lite.mdl.model.YAnnotEntity;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>YStruct Ref Pair</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link eu.jgen.notes.dmw.lite.base.lang.YStructRefPair#getStructproperty <em>Structproperty</em>}</li>
 *   <li>{@link eu.jgen.notes.dmw.lite.base.lang.YStructRefPair#getStructclass <em>Structclass</em>}</li>
 * </ul>
 *
 * @see eu.jgen.notes.dmw.lite.base.lang.LangPackage#getYStructRefPair()
 * @model
 * @generated
 */
public interface YStructRefPair extends EObject
{
  /**
   * Returns the value of the '<em><b>Structproperty</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Structproperty</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Structproperty</em>' reference.
   * @see #setStructproperty(YProperty)
   * @see eu.jgen.notes.dmw.lite.base.lang.LangPackage#getYStructRefPair_Structproperty()
   * @model
   * @generated
   */
  YProperty getStructproperty();

  /**
   * Sets the value of the '{@link eu.jgen.notes.dmw.lite.base.lang.YStructRefPair#getStructproperty <em>Structproperty</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Structproperty</em>' reference.
   * @see #getStructproperty()
   * @generated
   */
  void setStructproperty(YProperty value);

  /**
   * Returns the value of the '<em><b>Structclass</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Structclass</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Structclass</em>' reference.
   * @see #setStructclass(YAnnotEntity)
   * @see eu.jgen.notes.dmw.lite.base.lang.LangPackage#getYStructRefPair_Structclass()
   * @model
   * @generated
   */
  YAnnotEntity getStructclass();

  /**
   * Sets the value of the '{@link eu.jgen.notes.dmw.lite.base.lang.YStructRefPair#getStructclass <em>Structclass</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Structclass</em>' reference.
   * @see #getStructclass()
   * @generated
   */
  void setStructclass(YAnnotEntity value);

} // YStructRefPair
