/*
 * generated by Xtext 2.15.0
 */
package eu.jgen.notes.dmw.lite.base.scoping;

import eu.jgen.notes.dmw.lite.mdl.scoping.ModelScopeProvider;

public abstract class AbstractLangScopeProvider extends ModelScopeProvider {
}
